[package]
#####################################################
name = "kraken-runtime"
# ========================
version.workspace = true
edition.workspace = true
# ========================
publish = false

[features]
#####################################################
default = ["tokio"]
# ========================
tokio = ["dep:tokio"]
cycle = ["dep:cycle"]
# ========================


[dependencies]
#####################################################
tokio = { workspace = true, optional = true }
cycle = { git = "https://github.com/jamesgober/cycle", optional = true }
serde = { workspace = true }
regex = "1.10"
unicode-normalization = "0.1"
unicode-segmentation = "1.11"
ed25519-dalek = { version = "2.1", features = ["rand_core"] }
rand = "0.8"
chrono-tz = "0.8"
chrono = "0.4"
signal-hook = "0.3"
ctrlc = "3.4"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"