// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
int64_t kr_test_or_patterns();
int64_t kr_test_guard_clauses();
int64_t kr_test_combined_patterns();
int64_t kr_test_edge_cases();
int64_t kr_main();

int64_t kr_test_or_patterns() {
    kr_test_section("Or Patterns");
    int64_t x = 2;
    if (x == 1) {
        |;
        2 | 3;
        ->;
        {;
        kr_test_pass("Or pattern matches 2");
    }
    else {
        kr_test_fail("Should match or pattern");
    }
    int64_t y = 5;
    if (y == 1) {
        |;
        2 | 3;
        ->;
        {;
        kr_test_fail("Should not match");
    }
    else if (y == 4) {
        |;
        5 | 6;
        ->;
        {;
        kr_test_pass("Or pattern matches 5");
    }
    else {
        kr_test_fail("Should match second or pattern");
    }
    int64_t z = 10;
    if (z == 10) {
        kr_test_pass("Single value pattern matches");
    }
    else {
        kr_test_fail("Should match single value");
    }
    int64_t val = 7;
    if (val == 1) {
        |;
        2;
        ->;
        {;
        kr_test_fail("Should not match 1|2");
    }
    else if (val == 3) {
        |;
        4 | 5;
        ->;
        {;
        kr_test_fail("Should not match 3|4|5");
    }
    else if (val == 6) {
        |;
        7 | 8;
        ->;
        {;
        kr_test_pass("Matches 6|7|8");
    }
    else {
        kr_test_fail("Should match third or pattern");
    }
    0;
}

int64_t kr_test_guard_clauses() {
    kr_test_section("Guard Clauses");
    int64_t x = 15;
    {
        x > 10;
        ->;
        {;
        kr_test_pass("Guard clause x > 10 matches 15");
    }
    else {
        kr_test_fail("Should match guard");
    }
    int64_t y = 5;
    {
        y > 10;
        ->;
        {;
        kr_test_fail("Guard should not match");
    }
    else {
        kr_test_pass("Wildcard matches when guard fails");
    }
    int64_t z = 25;
    {
        z < 10;
        ->;
        {;
        kr_test_fail("First guard should not match");
    }
    else {
        z < 20;
        ->;
        {;
        kr_test_fail("Second guard should not match");
    }
    else {
        z >= 20;
        ->;
        {;
        kr_test_pass("Third guard matches");
    }
    else {
        kr_test_fail("Should match third guard");
    }
    int64_t val = 12;
    {
        _KR_EQ(val % 2, 0);
        ->;
        {;
        kr_test_pass("Guard with modulo matches even number");
    }
    else {
        kr_test_fail("Should match even guard");
    }
    int64_t target = 42;
    {
        _KR_EQ(target, 42);
        ->;
        {;
        kr_test_pass("Guard with equality matches");
    }
    else {
        kr_test_fail("Should match equality guard");
    }
    0;
}

int64_t kr_test_combined_patterns() {
    kr_test_section("Combined Or Patterns and Guards");
    int64_t x = 15;
    if (x == 10) {
        |;
        15 | 20;
        if (x > 12) {
            {;
            kr_test_pass("Or pattern with guard matches 15");
        }
        _;
        ->;
        {;
        kr_test_fail("Should match or pattern with guard");
    }
    int64_t y = 10;
    if (y == 10) {
        |;
        15 | 20;
        if (y > 12) {
            {;
            kr_test_fail("Guard should fail for 10");
        }
        10 | 15 | 20;
        ->;
        {;
        kr_test_pass("Or pattern without guard matches 10");
    }
    else {
        kr_test_fail("Should match or pattern");
    }
    int64_t z = 25;
    if (z == 1) {
        |;
        2 | 3;
        if (z < 5) {
            {;
            kr_test_fail("First or+guard should not match");
        }
        20 | 25 | 30;
        if (z >= 20) {
            {;
            kr_test_pass("Second or+guard matches");
        }
        _;
        ->;
        {;
        kr_test_fail("Should match second or+guard");
    }
    0;
}

int64_t kr_test_edge_cases() {
    kr_test_section("Edge Cases");
    int64_t x = 7;
    if (x == 1) {
        |;
        2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;
        ->;
        {;
        kr_test_pass("Large or pattern matches");
    }
    else {
        kr_test_fail("Should match large or pattern");
    }
    int64_t y = 100;
    int64_t threshold = 50;
    {
        y > threshold;
        ->;
        {;
        kr_test_pass("Guard with variable comparison works");
    }
    else {
        kr_test_fail("Should match guard with variable");
    }
    int64_t outer = 5;
    {
        outer > 0;
        ->;
        {;
        int64_t inner = outer * 2;
        {
            _KR_EQ(inner, 10);
            ->;
            {;
            kr_test_pass("Nested match with guards works");
        }
        else {
            kr_test_fail("Inner match should succeed");
        }
    }
    else {
        kr_test_fail("Outer match should succeed");
    }
    int64_t zero = 0;
    if (zero == 0) {
        |;
        1 | 2;
        ->;
        {;
        kr_test_pass("Or pattern matches zero");
    }
    else {
        kr_test_fail("Should match or pattern with zero");
    }
    int64_t neg = -5;
    {
        neg < 0;
        ->;
        {;
        kr_test_pass("Guard matches negative number");
    }
    else {
        kr_test_fail("Should match negative guard");
    }
    0;
}

int64_t kr_main() {
    kr_puts("=== ADVANCED PATTERNS TESTS ===");
    kr_puts("");
    kr_test_or_patterns();
    kr_test_guard_clauses();
    kr_test_combined_patterns();
    kr_test_edge_cases();
    kr_puts("");
    kr_puts("=== ALL TESTS PASSED ===");
    0;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
