// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
void kr_compose(void* f, void* int, void* ,, void* (, void* int, void* (, void* int, f x, x g);
void kr_pipe(void* f, void* int, void* ,, void* (, void* int, void* (, void* int, g x, x f);
void kr_test_basic_composition();
void kr_test_pipe_composition();
void kr_test_triple_composition();
void kr_test_composition_chain();
void kr_test_identity_composition();
void kr_test_composition_with_captures();
void kr_test_composition_factory();
void kr_test_self_composition();
void kr_test_composition_with_conditionals();
void kr_test_partial_application_composition();
void kr_test_composition_with_multiple_types();
void kr_test_composition_associativity();
void kr_test_composition_with_state();
void kr_test_higher_order_composition();
void kr_test_composition_with_closures_returning_closures();
void kr_test_composition_pipeline();
void kr_test_composition_with_filtering();
void kr_test_composition_memoization_style();
void kr_main();

void kr_compose(void* f, void* int, void* ,, void* (, void* int, void* (, void* int, f x, x g) {
}

void kr_pipe(void* f, void* int, void* ,, void* (, void* int, void* (, void* int, g x, x f) {
}

void kr_test_basic_composition() {
    __auto_type double = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x * 2;
}

void kr_test_pipe_composition() {
    __auto_type double = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x * 2;
}

void kr_test_triple_composition() {
    __auto_type f = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x + 1;
}

void kr_test_composition_chain() {
    __auto_type add1 = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x + 1;
}

void kr_test_identity_composition() {
    __auto_type identity = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x;
}

void kr_test_composition_with_captures() {
    __auto_type offset = 10;
    __auto_type add_offset = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x + offset;
}

void kr_test_composition_factory() {
    fn;
    kr_make_adder(n, int);
    ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    x | x + n;
}

void* kr_make_multiplier(int64_t n) {
    int;
    );
    ->;
    int;
    {;
    return |;
    x | x * n;
}

void kr_test_self_composition() {
    __auto_type double = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x * 2;
}

void kr_test_composition_with_conditionals() {
    __auto_type abs = |;
    x;
    :;
    int | ->;
    int;
    {;
    if (x < 0) {
        return -x;
    }
    else {
        return x;
    }
}

void kr_test_partial_application_composition() {
    fn;
    kr_curry_add(x, int);
    ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    y | x + y;
}

void kr_test_composition_with_multiple_types() {
    __auto_type to_string = |;
    x;
    :;
    int | ->;
    string;
    {;
    return "value";
}

void kr_test_composition_associativity() {
    __auto_type f = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x + 1;
}

void kr_test_composition_with_state() {
    int64_t mut;
    counter = 0;
    __auto_type increment_counter = |;
    x;
    :;
    int | ->;
    int;
    {;
    counter = counter + 1;
    return x;
}

void kr_test_higher_order_composition() {
    fn;
    kr_compose_twice(f, fn(int), int);
    ->;
    fn(int);
    ->;
    int;
    {;
    return kr_compose(f, f);
}

void kr_test_composition_with_closures_returning_closures() {
    __auto_type make_adder = |;
    n;
    :;
    int | ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    x | x + n;
}

int64_t kr_(() {
    return kr_compose(kr_make_adder(a), kr_make_adder(b));
}

void kr_test_composition_pipeline() {
    __auto_type operations = [ | x;
    :;
    int | ->;
    int;
    {;
    return x + 1;
}

void kr_test_composition_with_filtering() {
    __auto_type is_positive = |;
    x;
    :;
    int | ->;
    bool;
    {;
    return x > 0;
}

void kr_test_composition_memoization_style() {
    int64_t mut;
    cache = 0;
    int64_t mut;
    cached = false;
    __auto_type expensive = |;
    x;
    :;
    int | ->;
    int;
    {;
    if (!cached) {
        cache = x * x;
        cached = true;
    }
    return cache;
}

void kr_main() {
    kr_test_basic_composition();
    kr_test_pipe_composition();
    kr_test_triple_composition();
    kr_test_composition_chain();
    kr_test_identity_composition();
    kr_test_composition_with_captures();
    kr_test_composition_factory();
    kr_test_self_composition();
    kr_test_composition_with_conditionals();
    kr_test_partial_application_composition();
    kr_test_composition_with_multiple_types();
    kr_test_composition_associativity();
    kr_test_composition_with_state();
    kr_test_higher_order_composition();
    kr_test_composition_with_closures_returning_closures();
    kr_test_composition_pipeline();
    kr_test_composition_with_filtering();
    kr_test_composition_memoization_style();
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
