// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
typedef struct Point Point;
void kr_test_capture_by_reference();
void kr_test_capture_multiple_vars();
void kr_test_capture_by_value_move();
void kr_test_nested_capture();
void kr_test_capture_in_loop();
void kr_test_capture_mutable_reference();
void kr_test_capture_from_parameter();
void kr_test_capture_struct_field();
void kr_test_capture_array_element();
void kr_test_mixed_captures();
void kr_test_capture_in_conditional();
void kr_test_capture_shadowing();
void kr_test_no_capture();
void kr_test_capture_string();
void kr_test_capture_bool();
void kr_test_deep_nesting();
void kr_test_closure_array();
void kr_test_move_prevents_later_use();
void kr_main();

struct Point {
int64_t x;
void* ,;
void* int;
void* let;
x Point;
void* :;
void* y;
};

void kr_test_capture_by_reference() {
    __auto_type x = 10;
    __auto_type closure = |;
    y;
    :;
    int | ->;
    int;
    {;
    return x + y;
}

void kr_test_capture_multiple_vars() {
    __auto_type a = 1;
    __auto_type b = 2;
    __auto_type c = 3;
    __auto_type closure = ||;
    a + b + c;
    __auto_type result = kr_closure();
}

void kr_test_capture_by_value_move() {
    __auto_type x = 42;
    __auto_type closure = move | y;
    :;
    int | ->;
    int;
    {;
    return x + y;
}

void kr_test_nested_capture() {
    __auto_type outer = 10;
    __auto_type inner_closure = ||;
    {;
    __auto_type middle = 20;
    __auto_type innermost = ||;
    outer + middle;
    return kr_innermost();
}

void kr_test_capture_in_loop() {
    __auto_type sum = 0;
    __auto_type arr = [;
    1;
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ];
    for (i; arr; {) {
        = | x;
        :;
        int | ->;
        int;
        {;
        return sum + x;
    }
    sum = kr_add_to_sum(i);
}

void kr_test_capture_mutable_reference() {
    int64_t mut;
    counter = 0;
    __auto_type increment = ||;
    {;
    counter = counter + 1;
    return counter;
}

void kr_test_capture_from_parameter() {
    fn;
    kr_make_adder(x, int);
    ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    y | x + y;
}

void kr_test_capture_struct_field() {
    struct;
    (Point){.x = int, .y = int};
    __auto_type p = (Point){.x = 10, .y = 20};
    __auto_type get_x = ||;
    p.x;
    __auto_type get_y = ||;
    p.y;
    __auto_type x_val = kr_get_x();
    __auto_type y_val = kr_get_y();
}

void kr_test_capture_array_element() {
    __auto_type arr = [;
    1;
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ];
    __auto_type get_first = ||;
    arr[0];
    __auto_type get_last = ||;
    arr[4];
    __auto_type first = kr_get_first();
    __auto_type last = kr_get_last();
}

void kr_test_mixed_captures() {
    __auto_type a = 1;
    __auto_type b = 2;
    __auto_type c = 3;
    __auto_type closure = |;
    c;
    :;
    int | ->;
    int;
    {;
    return a + b + c;
}

void kr_test_capture_in_conditional() {
    __auto_type flag = true;
    __auto_type x = 10;
    __auto_type y = 20;
    __auto_type closure = ||;
    {;
    if (flag) {
        return x;
    }
    else {
        return y;
    }
}

void kr_test_capture_shadowing() {
    __auto_type x = 10;
    __auto_type closure = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x * 2;
}

void kr_test_no_capture() {
    __auto_type closure = |;
    x;
    :;
    int;
    ,;
    y;
    :;
    int | ->;
    int;
    {;
    return x + y;
}

void kr_test_capture_string() {
    __auto_type message = "Hello";
    __auto_type greet = |;
    name;
    :;
    string | ->;
    string;
    {;
    return message + ", " + name;
}

void kr_test_capture_bool() {
    __auto_type is_valid = true;
    __auto_type check = ||;
    is_valid;
    __auto_type result = kr_check();
}

void kr_test_deep_nesting() {
    __auto_type a = 1;
    __auto_type level1 = ||;
    {;
    __auto_type b = 2;
    __auto_type level2 = ||;
    {;
    __auto_type c = 3;
    __auto_type level3 = ||;
    {;
    return a + b + c;
}

void kr_test_closure_array() {
    __auto_type x = 10;
    __auto_type closures = [ | y;
    :;
    int | ->;
    int;
    {;
    return x + y;
}

void kr_test_move_prevents_later_use() {
    __auto_type x = 42;
    __auto_type closure = move || x;
    __auto_type result = kr_closure();
}

void kr_main() {
    kr_test_capture_by_reference();
    kr_test_capture_multiple_vars();
    kr_test_capture_by_value_move();
    kr_test_nested_capture();
    kr_test_capture_in_loop();
    kr_test_capture_mutable_reference();
    kr_test_capture_from_parameter();
    kr_test_capture_struct_field();
    kr_test_capture_array_element();
    kr_test_mixed_captures();
    kr_test_capture_in_conditional();
    kr_test_capture_shadowing();
    kr_test_no_capture();
    kr_test_capture_string();
    kr_test_capture_bool();
    kr_test_deep_nesting();
    kr_test_closure_array();
    kr_test_move_prevents_later_use();
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
