// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>
#include <math.h>
#include <time.h>
#include <ctype.h>
#include <stdarg.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef struct { int64_t f0; } KrTuple1;
typedef struct { int64_t f0; int64_t f1; } KrTuple2;
typedef struct { int64_t f0; int64_t f1; int64_t f2; } KrTuple3;
typedef struct { int64_t f0; int64_t f1; int64_t f2; int64_t f3; } KrTuple4;
typedef struct { int64_t f0; int64_t f1; int64_t f2; int64_t f3; int64_t f4; } KrTuple5;
typedef struct { int64_t f0; int64_t f1; int64_t f2; int64_t f3; int64_t f4; int64_t f5; } KrTuple6;
typedef struct { int64_t f0; int64_t f1; int64_t f2; int64_t f3; int64_t f4; int64_t f5; int64_t f6; } KrTuple7;
typedef struct { int64_t f0; int64_t f1; int64_t f2; int64_t f3; int64_t f4; int64_t f5; int64_t f6; int64_t f7; } KrTuple8;
typedef struct { int64_t f0; int64_t f1; int64_t f2; int64_t f3; int64_t f4; int64_t f5; int64_t f6; int64_t f7; int64_t f8; } KrTuple9;
typedef struct { int64_t f0; int64_t f1; int64_t f2; int64_t f3; int64_t f4; int64_t f5; int64_t f6; int64_t f7; int64_t f8; int64_t f9; } KrTuple10;
typedef struct { void* data; void* vtable; } KrDyn;
static inline int64_t _kr_box(const void* src, size_t n) { void* p = malloc(n); memcpy(p, src, n); return (int64_t)p; }
typedef int64_t (*KrClosure)(void*,int64_t);
#define _KR_CL_FN(cl) ((void*)(*(int64_t*)(cl)))
#define _KR_CL_ENV(cl) ((void*)((int64_t*)(cl) + 1))
static void* _kr_cl_alloc(void* fn, int n, ...) {
  int64_t* cl = (int64_t*)malloc((1+n)*sizeof(int64_t));
  cl[0] = (int64_t)fn; va_list a; va_start(a,n);
  for(int i=0;i<n;i++) cl[1+i]=va_arg(a,int64_t);
  va_end(a); return (void*)cl;
}
static int64_t _kr_cl_call0(void* cl) {
  return ((int64_t(*)(void*))_KR_CL_FN(cl))(_KR_CL_ENV(cl));
}
static int64_t _kr_cl_call1(void* cl, int64_t a) {
  return ((int64_t(*)(void*,int64_t))_KR_CL_FN(cl))(_KR_CL_ENV(cl), a);
}
static int64_t _kr_cl_call2(void* cl, int64_t a, int64_t b) {
  return ((int64_t(*)(void*,int64_t,int64_t))_KR_CL_FN(cl))(_KR_CL_ENV(cl), a, b);
}
static int64_t _kr_cl_call3(void* cl, int64_t a, int64_t b, int64_t c) {
  return ((int64_t(*)(void*,int64_t,int64_t,int64_t))_KR_CL_FN(cl))(_KR_CL_ENV(cl), a, b, c);
}
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
void kr_print_int(int64_t v) { printf("%lld", (long long)v); }
int64_t kr_strlen(kr_str s, ...) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { if((uintptr_t)a<4096||(uintptr_t)b<4096)return (int)((intptr_t)a-(intptr_t)b); return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { if(!a&&!b)return 1; if(!a||!b)return 0; return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { if(!a&&!b)return 0; if(!a||!b)return 1; return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_ADD(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), kr_str_concat((char*)(a),(char*)(b)), ((int64_t)(a) + (int64_t)(b)))
#define _KR_LEN(x) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(x), char*), (int64_t)strlen((char*)(x)), kr_vec_int_len((void*)(intptr_t)(x)))
kr_str kr_fmt_int(int64_t v);
#define _KR_TO_STRING(x) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(x), char*), (char*)(x), kr_fmt_int((int64_t)(x)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
int64_t kr_fclose(void* f) { return (int64_t)fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }
int64_t kr_vec_int_pop(void* vp) { KrVecInt* v = (KrVecInt*)vp; return v->data[--v->len]; }
void kr_vec_int_clear(void* vp) { ((KrVecInt*)vp)->len = 0; }
int64_t kr_vec_int_capacity(void* vp) { return ((KrVecInt*)vp)->cap; }
void kr_vec_int_reserve(void* vp, int64_t n) {
  KrVecInt* v = (KrVecInt*)vp; if(n>v->cap){v->cap=n;v->data=(int64_t*)realloc(v->data,n*sizeof(int64_t));}
}
void* kr_vec_int_with_capacity(int64_t n) {
  KrVecInt* v=(KrVecInt*)malloc(sizeof(KrVecInt));v->data=(int64_t*)malloc(n*sizeof(int64_t));v->len=0;v->cap=n;return v;
}
void kr_vec_int_insert(void* vp, int64_t i, int64_t val) {
  KrVecInt* v=(KrVecInt*)vp; kr_vec_int_push(vp,0); memmove(&v->data[i+1],&v->data[i],(v->len-i-1)*sizeof(int64_t)); v->data[i]=val;
}
int64_t kr_vec_int_remove(void* vp, int64_t i) {
  KrVecInt* v=(KrVecInt*)vp; int64_t val=v->data[i]; memmove(&v->data[i],&v->data[i+1],(v->len-i-1)*sizeof(int64_t)); v->len--; return val;
}
int64_t kr_vec_int_swap_remove(void* vp, int64_t i) { KrVecInt* v=(KrVecInt*)vp; int64_t val=v->data[i]; v->data[i]=v->data[--v->len]; return val; }
void kr_vec_int_shrink_to_fit(void* vp) { KrVecInt* v=(KrVecInt*)vp; if(v->len<v->cap){v->cap=v->len?v->len:1;v->data=(int64_t*)realloc(v->data,v->cap*sizeof(int64_t));} }
void* _kr_vec_int_of(int n, ...) {
  void* v=kr_vec_int_new(); va_list a; va_start(a,n);
  for(int i=0;i<n;i++) kr_vec_int_push(v,va_arg(a,int64_t));
  va_end(a); return v;
}
kr_str kr_vec_string_pop(void* vp) { KrVecString* v = (KrVecString*)vp; return v->data[--v->len]; }
void kr_vec_string_clear(void* vp) { ((KrVecString*)vp)->len = 0; }
int64_t kr_vec_string_capacity(void* vp) { return ((KrVecString*)vp)->cap; }
void kr_vec_string_reserve(void* vp, int64_t n) {
  KrVecString* v = (KrVecString*)vp; if(n>v->cap){v->cap=n;v->data=(char**)realloc(v->data,n*sizeof(char*));}
}
void* kr_vec_string_with_capacity(int64_t n) {
  KrVecString* v=(KrVecString*)malloc(sizeof(KrVecString));v->data=(char**)malloc(n*sizeof(char*));v->len=0;v->cap=n;return v;
}
void kr_vec_string_shrink_to_fit(void* vp) { KrVecString* v=(KrVecString*)vp; if(v->len<v->cap){v->cap=v->len?v->len:1;v->data=(char**)realloc(v->data,v->cap*sizeof(char*));} }
void* _kr_vec_string_of(int n, ...) {
  void* v=kr_vec_string_new(); va_list a; va_start(a,n);
  for(int i=0;i<n;i++) kr_vec_string_push(v,va_arg(a,kr_str));
  va_end(a); return v;
}
kr_str kr_vec_string_swap_remove(void* vp, int64_t i) { KrVecString* v=(KrVecString*)vp; kr_str val=v->data[i]; v->data[i]=v->data[--v->len]; return val; }
typedef struct { void** data; int64_t len; int64_t cap; } KrVecBytes;
void* kr_vec_bytes_new() { KrVecBytes* v=(KrVecBytes*)malloc(sizeof(KrVecBytes)); v->data=(void**)malloc(16*sizeof(void*)); v->len=0; v->cap=16; return v; }
void kr_vec_bytes_push(void* vp, int64_t val) { KrVecBytes* v=(KrVecBytes*)vp; if(v->len>=v->cap){v->cap*=2;v->data=(void**)realloc(v->data,v->cap*sizeof(void*));} v->data[v->len++]=(void*)(intptr_t)val; }
int64_t kr_vec_bytes_get(void* vp, int64_t i) { return (int64_t)(intptr_t)((KrVecBytes*)vp)->data[i]; }
void kr_vec_bytes_set(void* vp, int64_t i, int64_t val) { ((KrVecBytes*)vp)->data[i]=(void*)(intptr_t)val; }
int64_t kr_vec_bytes_len(void* vp) { return ((KrVecBytes*)vp)->len; }
void kr_vec_bytes_free(void* vp) { KrVecBytes* v=(KrVecBytes*)vp; free(v->data); free(v); }
int64_t kr_vec_bytes_pop(void* vp) { KrVecBytes* v=(KrVecBytes*)vp; return (int64_t)(intptr_t)v->data[--v->len]; }
void kr_vec_bytes_clear(void* vp) { ((KrVecBytes*)vp)->len=0; }
int64_t kr_vec_bytes_capacity(void* vp) { return ((KrVecBytes*)vp)->cap; }
void kr_vec_bytes_reserve(void* vp, int64_t n) { KrVecBytes* v=(KrVecBytes*)vp; if(n>v->cap){v->cap=n;v->data=(void**)realloc(v->data,n*sizeof(void*));} }
void* kr_vec_bytes_with_capacity(int64_t n) { KrVecBytes* v=(KrVecBytes*)malloc(sizeof(KrVecBytes)); v->data=(void**)malloc(n*sizeof(void*)); v->len=0; v->cap=n; return v; }
void kr_vec_bytes_shrink_to_fit(void* vp) { KrVecBytes* v=(KrVecBytes*)vp; if(v->len<v->cap){v->cap=v->len?v->len:1;v->data=(void**)realloc(v->data,v->cap*sizeof(void*));} }
int64_t kr_vec_bytes_swap_remove(void* vp, int64_t i) { KrVecBytes* v=(KrVecBytes*)vp; void* val=v->data[i]; v->data[i]=v->data[--v->len]; return (int64_t)(intptr_t)val; }
typedef struct { char** keys; int64_t* vals; int64_t cap; int64_t len; } KrMapSI;
static uint64_t _kr_hash_str(const char* s) { uint64_t h=5381; while(*s) h=h*33+(*s++); return h; }
void* kr_map_string_int_new() {
  KrMapSI* m=(KrMapSI*)malloc(sizeof(KrMapSI)); m->cap=256; m->len=0;
  m->keys=(char**)calloc(256,sizeof(char*)); m->vals=(int64_t*)calloc(256,sizeof(int64_t)); return m;
}
static void _kr_mapsi_grow(KrMapSI* m) {
  int64_t oc=m->cap; char** ok=m->keys; int64_t* ov=m->vals;
  m->cap=oc*2; m->keys=(char**)calloc(m->cap,sizeof(char*)); m->vals=(int64_t*)calloc(m->cap,sizeof(int64_t)); m->len=0;
  for(int64_t i=0;i<oc;i++){if(ok[i]){uint64_t h=_kr_hash_str(ok[i])%m->cap;
    while(m->keys[h]) h=(h+1)%m->cap; m->keys[h]=ok[i]; m->vals[h]=ov[i]; m->len++;}} free(ok);free(ov);
}
void kr_map_string_int_set(void* mp, kr_str key, int64_t val) {
  KrMapSI* m=(KrMapSI*)mp;
  if(m->len*10 >= m->cap*7) _kr_mapsi_grow(m);
  uint64_t h=_kr_hash_str(key)%m->cap;
  while(m->keys[h]){if(strcmp(m->keys[h],key)==0){m->vals[h]=val;return;} h=(h+1)%m->cap;}
  m->keys[h]=strdup(key); m->vals[h]=val; m->len++;
}
int64_t kr_map_string_int_get(void* mp, kr_str key) {
  KrMapSI* m=(KrMapSI*)mp; uint64_t h=_kr_hash_str(key)%m->cap;
  while(m->keys[h]){if(strcmp(m->keys[h],key)==0) return m->vals[h]; h=(h+1)%m->cap;} return 0;
}
int64_t kr_map_string_int_has(void* mp, kr_str key) {
  KrMapSI* m=(KrMapSI*)mp; uint64_t h=_kr_hash_str(key)%m->cap;
  while(m->keys[h]){if(strcmp(m->keys[h],key)==0) return 1; h=(h+1)%m->cap;} return 0;
}
int64_t kr_map_string_int_len(void* mp) { return ((KrMapSI*)mp)->len; }
void kr_map_string_int_delete(void* mp, kr_str key) {
  KrMapSI* m=(KrMapSI*)mp; uint64_t h=_kr_hash_str(key)%m->cap;
  while(m->keys[h]){if(strcmp(m->keys[h],key)==0){free(m->keys[h]);m->keys[h]=NULL;m->len--;return;} h=(h+1)%m->cap;}
}
void kr_map_string_int_clear(void* mp) { KrMapSI* m=(KrMapSI*)mp; for(int64_t i=0;i<m->cap;i++){if(m->keys[i])free(m->keys[i]);m->keys[i]=NULL;} m->len=0; }
void kr_map_string_int_free(void* mp) { KrMapSI* m=(KrMapSI*)mp; for(int64_t i=0;i<m->cap;i++)if(m->keys[i])free(m->keys[i]); free(m->keys);free(m->vals);free(m); }
void* kr_map_string_int_keys(void* mp) { KrMapSI* m=(KrMapSI*)mp; void* v=kr_vec_string_new(); for(int64_t i=0;i<m->cap;i++)if(m->keys[i])kr_vec_string_push(v,m->keys[i]); return v; }
void* kr_map_string_int_values(void* mp) { KrMapSI* m=(KrMapSI*)mp; void* v=kr_vec_int_new(); for(int64_t i=0;i<m->cap;i++)if(m->keys[i])kr_vec_int_push(v,m->vals[i]); return v; }
typedef struct { char** keys; char** vals; int64_t cap; int64_t len; } KrMapSS;
void* kr_map_string_string_new() {
  KrMapSS* m=(KrMapSS*)malloc(sizeof(KrMapSS)); m->cap=256; m->len=0;
  m->keys=(char**)calloc(256,sizeof(char*)); m->vals=(char**)calloc(256,sizeof(char*)); return m;
}
static void _kr_mapss_grow(KrMapSS* m) {
  int64_t oc=m->cap; char** ok=m->keys; char** ov=m->vals;
  m->cap=oc*2; m->keys=(char**)calloc(m->cap,sizeof(char*)); m->vals=(char**)calloc(m->cap,sizeof(char*)); m->len=0;
  for(int64_t i=0;i<oc;i++){if(ok[i]){uint64_t h=_kr_hash_str(ok[i])%m->cap;
    while(m->keys[h]) h=(h+1)%m->cap; m->keys[h]=ok[i]; m->vals[h]=ov[i]; m->len++;}} free(ok);free(ov);
}
void kr_map_string_string_set(void* mp, kr_str key, kr_str val) {
  KrMapSS* m=(KrMapSS*)mp;
  if(m->len*10 >= m->cap*7) _kr_mapss_grow(m);
  uint64_t h=_kr_hash_str(key)%m->cap;
  while(m->keys[h]){if(strcmp(m->keys[h],key)==0){free(m->vals[h]);m->vals[h]=strdup(val);return;} h=(h+1)%m->cap;}
  m->keys[h]=strdup(key); m->vals[h]=strdup(val); m->len++;
}
kr_str kr_map_string_string_get(void* mp, kr_str key) {
  KrMapSS* m=(KrMapSS*)mp; uint64_t h=_kr_hash_str(key)%m->cap;
  while(m->keys[h]){if(strcmp(m->keys[h],key)==0) return m->vals[h]; h=(h+1)%m->cap;} return "";
}
int64_t kr_map_string_string_has(void* mp, kr_str key) {
  KrMapSS* m=(KrMapSS*)mp; uint64_t h=_kr_hash_str(key)%m->cap;
  while(m->keys[h]){if(strcmp(m->keys[h],key)==0) return 1; h=(h+1)%m->cap;} return 0;
}
int64_t kr_map_string_string_len(void* mp) { return ((KrMapSS*)mp)->len; }
void kr_map_string_string_delete(void* mp, kr_str key) {
  KrMapSS* m=(KrMapSS*)mp; uint64_t h=_kr_hash_str(key)%m->cap;
  while(m->keys[h]){if(strcmp(m->keys[h],key)==0){free(m->keys[h]);free(m->vals[h]);m->keys[h]=NULL;m->vals[h]=NULL;m->len--;return;} h=(h+1)%m->cap;}
}
void kr_map_string_string_clear(void* mp) { KrMapSS* m=(KrMapSS*)mp; for(int64_t i=0;i<m->cap;i++){if(m->keys[i]){free(m->keys[i]);free(m->vals[i]);m->keys[i]=NULL;m->vals[i]=NULL;}} m->len=0; }
void kr_map_string_string_free(void* mp) { KrMapSS* m=(KrMapSS*)mp; for(int64_t i=0;i<m->cap;i++){if(m->keys[i]){free(m->keys[i]);free(m->vals[i]);}} free(m->keys);free(m->vals);free(m); }
void* kr_map_string_string_keys(void* mp) { KrMapSS* m=(KrMapSS*)mp; void* v=kr_vec_string_new(); for(int64_t i=0;i<m->cap;i++)if(m->keys[i])kr_vec_string_push(v,m->keys[i]); return v; }
void* kr_map_string_string_values(void* mp) { KrMapSS* m=(KrMapSS*)mp; void* v=kr_vec_string_new(); for(int64_t i=0;i<m->cap;i++)if(m->keys[i])kr_vec_string_push(v,m->vals[i]); return v; }
kr_str kr_fmt_float(double v, ...) { char* r=(char*)malloc(64); snprintf(r,64,"%g",v); return r; }
kr_str kr_fmt_bool(int64_t v) { return v ? "true" : "false"; }
kr_str kr_fmt_hex(int64_t v) { char* r=(char*)malloc(32); snprintf(r,32,"0x%llx",(unsigned long long)v); return r; }
#define kr_printf(...) printf(__VA_ARGS__)
void kr_putchar(int64_t c) { putchar((int)c); }
int64_t kr_getchar() { return (int64_t)getchar(); }
void* kr_malloc(int64_t sz) { return malloc((size_t)sz); }
void kr_free(void* p) { free(p); }
void* kr_realloc(void* p, int64_t sz) { return realloc(p,(size_t)sz); }
int64_t kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
int64_t kr_str_ne(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
int64_t kr_str_len(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_str_contains(kr_str s, kr_str sub) { return strstr(s,sub)!=NULL; }
int64_t kr_str_starts_with(kr_str s, kr_str pfx) { return strncmp(s,pfx,strlen(pfx))==0; }
int64_t kr_str_index_of(kr_str s, kr_str sub) { char* p=strstr(s,sub); return p?(int64_t)(p-s):-1; }
kr_str kr_str_replace(kr_str s, kr_str old, kr_str rep) {
  size_t ol=strlen(old),rl=strlen(rep),sl=strlen(s); char* r=(char*)malloc(sl*2+1); char* w=r;
  if(!ol){strcpy(r,s);return r;}
  while(*s){char* p=strstr(s,old);if(!p){strcpy(w,s);return r;}memcpy(w,s,p-s);w+=p-s;memcpy(w,rep,rl);w+=rl;s=p+ol;}*w=0;return r;
}
kr_str kr_str_to_lower(kr_str s) { size_t n=strlen(s); char* r=(char*)malloc(n+1); for(size_t i=0;i<=n;i++)r[i]=tolower((unsigned char)s[i]); return r; }
kr_str kr_str_to_upper(kr_str s) { size_t n=strlen(s); char* r=(char*)malloc(n+1); for(size_t i=0;i<=n;i++)r[i]=toupper((unsigned char)s[i]); return r; }
kr_str kr_str_trim(kr_str s) { while(*s==' '||*s=='\t'||*s=='\n'||*s=='\r')s++; size_t n=strlen(s); while(n>0&&(s[n-1]==' '||s[n-1]=='\t'||s[n-1]=='\n'||s[n-1]=='\r'))n--; char* r=(char*)malloc(n+1); memcpy(r,s,n); r[n]=0; return r; }
kr_str kr_strdup(kr_str s) { return strdup(s); }
kr_str kr_from_cstr(void* p) { return p ? (kr_str)p : ""; }
void* kr_cstr(kr_str s) { return (void*)s; }
int64_t kr_str_char_count(kr_str s) { return (int64_t)strlen(s); }
kr_str kr_str_from_char_code(int64_t c) { char* r=(char*)malloc(2); r[0]=(char)c; r[1]=0; return r; }
kr_str kr_str_join(void* vp, kr_str sep) {
  KrVecString* v=(KrVecString*)vp; if(!v->len) return ""; size_t total=0,sl=strlen(sep);
  for(int64_t i=0;i<v->len;i++) total+=strlen(v->data[i]); total+=(v->len-1)*sl;
  char* r=(char*)malloc(total+1); char* w=r;
  for(int64_t i=0;i<v->len;i++){if(i>0){memcpy(w,sep,sl);w+=sl;}size_t n=strlen(v->data[i]);memcpy(w,v->data[i],n);w+=n;} *w=0; return r;
}
void* kr_str_split(kr_str s, kr_str sep) {
  void* v=kr_vec_string_new(); size_t sl=strlen(sep);
  while(*s){char* p=strstr(s,sep);if(!p){kr_vec_string_push(v,strdup(s));break;}
  char* chunk=(char*)malloc(p-s+1);memcpy(chunk,s,p-s);chunk[p-s]=0;kr_vec_string_push(v,chunk);s=p+sl;} return v;
}
int64_t kr_rand() { return (int64_t)rand(); }
void kr_srand(int64_t seed) { srand((unsigned)seed); }
double kr_sqrt(double x) { return sqrt(x); }
double kr_pow(double x, double y) { return pow(x,y); }
double kr_floor(double x) { return floor(x); }
double kr_ceil(double x) { return ceil(x); }
double kr_round(double x) { return round(x); }
double kr_sin(double x) { return sin(x); }
double kr_cos(double x) { return cos(x); }
double kr_tan(double x) { return tan(x); }
double kr_log(double x) { return log(x); }
double kr_log10(double x) { return log10(x); }
double kr_exp(double x) { return exp(x); }
double kr_fabs(double x) { return fabs(x); }
double kr_fmod(double x, double y) { return fmod(x,y); }
double kr_atan2(double y, double x) { return atan2(y,x); }
double kr_asin(double x) { return asin(x); }
double kr_acos(double x) { return acos(x); }
double kr_atan(double x) { return atan(x); }
double kr_sinh(double x) { return sinh(x); }
double kr_cosh(double x) { return cosh(x); }
double kr_tanh(double x) { return tanh(x); }
static int _kr_test_count=0, _kr_test_pass=0, _kr_test_fail=0;
static inline void _kr_default_test_section(kr_str name) { printf("--- %s ---\n", name); }
static inline void _kr_default_test_pass(kr_str msg) { _kr_test_count++; _kr_test_pass++; printf("  PASS: %s\n", msg); }
static inline void _kr_default_test_fail(kr_str msg) { _kr_test_count++; _kr_test_fail++; printf("  FAIL: %s\n", msg); }
static inline void _kr_default_test_skip(kr_str msg) { printf("  SKIP: %s\n", msg); }
static inline void _kr_default_assert(int64_t cond) { if(!cond){printf("ASSERTION FAILED\n");exit(1);} }
static inline void _kr_default_assert_eq(int64_t a, int64_t b) {
  _kr_test_count++; if(a==b){_kr_test_pass++;}else{_kr_test_fail++;printf("  ASSERT_EQ FAILED: %lld != %lld\n",(long long)a,(long long)b);}
}
static inline void _kr_default_assert_ne(int64_t a, int64_t b) {
  _kr_test_count++; if(a!=b){_kr_test_pass++;}else{_kr_test_fail++;printf("  ASSERT_NE FAILED: %lld == %lld\n",(long long)a,(long long)b);}
}
#define kr_test_section _kr_default_test_section
#define kr_test_pass _kr_default_test_pass
#define kr_test_fail _kr_default_test_fail
#define kr_test_skip _kr_default_test_skip
#define kr_assert _kr_default_assert
#define kr_assert_eq _kr_default_assert_eq
#define kr_assert_ne _kr_default_assert_ne
void* kr_mutex_create() { return malloc(64); }
void kr_mutex_destroy(void* m) { free(m); }
void kr_mutex_lock(void* m) { (void)m; }
void kr_mutex_unlock(void* m) { (void)m; }
void* kr_thread_spawn(void* fn) { (void)fn; return NULL; }
void kr_thread_join(void* h) { (void)h; }
void kr_join(void* h) { (void)h; }
int64_t kr_timeout(void* h, int64_t ms) { (void)h; (void)ms; return 0; }
void kr_sleep_ms(int64_t ms) { usleep((unsigned)(ms*1000)); }
int64_t kr_time() { return (int64_t)time(NULL); }
int64_t kr_isalpha(int64_t c) { return isalpha((int)c); }
int64_t kr_isdigit(int64_t c) { return isdigit((int)c); }
int64_t kr_isalnum(int64_t c) { return isalnum((int)c); }
int64_t kr_isupper(int64_t c) { return isupper((int)c); }
int64_t kr_islower(int64_t c) { return islower((int)c); }
int64_t kr_isspace(int64_t c) { return isspace((int)c); }
int64_t kr_tolower(int64_t c) { return (int64_t)tolower((int)c); }
int64_t kr_toupper(int64_t c) { return (int64_t)toupper((int)c); }
int64_t kr_atoi(kr_str s) { return (int64_t)atoi(s); }
double kr_atof(kr_str s) { return atof(s); }
void kr_abort() { abort(); }
kr_str kr_fgets(kr_str buf, int64_t n, void* f) { return fgets(buf,(int)n,(FILE*)f); }
int64_t kr_fwrite(void* ptr, int64_t size, int64_t count, void* f) { return (int64_t)fwrite(ptr,(size_t)size,(size_t)count,(FILE*)f); }
int64_t kr_fread(void* ptr, int64_t size, int64_t count, void* f) { return (int64_t)fread(ptr,(size_t)size,(size_t)count,(FILE*)f); }
int64_t kr_feof(void* f) { return (int64_t)feof((FILE*)f); }
int64_t kr_ferror(void* f) { return (int64_t)ferror((FILE*)f); }
int64_t kr_fflush(void* f) { return (int64_t)fflush((FILE*)f); }
int64_t kr_fgetc(void* f) { return (int64_t)fgetc((FILE*)f); }
int64_t kr_fputc(int64_t c, void* f) { return (int64_t)fputc((int)c,(FILE*)f); }
int64_t kr_fseek(void* f, int64_t off, int64_t w) { return (int64_t)fseek((FILE*)f,(long)off,(int)w); }
int64_t kr_ftell(void* f) { return (int64_t)ftell((FILE*)f); }
void kr_rewind(void* f) { rewind((FILE*)f); }
int64_t kr_memcmp(void* a, void* b, int64_t n) { return (int64_t)memcmp(a,b,(size_t)n); }
void* kr_memcpy(void* dst, void* src, int64_t n) { return memcpy(dst,src,(size_t)n); }
void* kr_memmove(void* dst, void* src, int64_t n) { return memmove(dst,src,(size_t)n); }
void* kr_memset(void* p, int64_t c, int64_t n) { return memset(p,(int)c,(size_t)n); }
int64_t kr_setenv(kr_str name, kr_str val, ...) { return (int64_t)setenv(name,val,1); }
void kr_unsetenv(kr_str name) { unsetenv(name); }
kr_str kr_strstr(kr_str haystack, kr_str needle) { char* p=strstr(haystack,needle); return p?p:""; }
kr_str kr_strchr(kr_str s, int64_t c) { char* p=strchr(s,(int)c); return p?p:""; }
kr_str kr_strncpy(kr_str dst, kr_str src, int64_t n) { return strncpy(dst,src,(size_t)n); }
kr_str kr_strcat(kr_str dst, kr_str src) { return strcat(dst,src); }
kr_str kr_strcpy(kr_str dst, kr_str src) { return strcpy(dst,src); }
int64_t kr_strncmp(kr_str a, kr_str b, int64_t n) { return (int64_t)strncmp(a,b,(size_t)n); }
kr_str kr_strtok(kr_str s, kr_str d) { return strtok(s,d); }
int64_t kr_str_is_valid_utf8(kr_str s) { while(*s){unsigned char c=*s;if(c<0x80)s++;else if((c&0xE0)==0xC0){if((s[1]&0xC0)!=0x80)return 0;s+=2;}else if((c&0xF0)==0xE0){if((s[1]&0xC0)!=0x80||(s[2]&0xC0)!=0x80)return 0;s+=3;}else if((c&0xF8)==0xF0){if((s[1]&0xC0)!=0x80||(s[2]&0xC0)!=0x80||(s[3]&0xC0)!=0x80)return 0;s+=4;}else return 0;} return 1; }
int64_t kr_str_char_at_utf8(kr_str s, int64_t idx) { return (int64_t)(unsigned char)s[idx]; }
int64_t kr_block_on(void* future) { (void)future; return 0; }
#define kr_sprintf(...) sprintf(__VA_ARGS__)
#define kr_sscanf(...) sscanf(__VA_ARGS__)
#define kr_snprintf(...) snprintf(__VA_ARGS__)
int64_t kr_rand_int(int64_t lo, int64_t hi) { return lo + (rand() % (hi - lo + 1)); }
double kr_rand_float() { return (double)rand() / (double)RAND_MAX; }
void kr_rand_seed(int64_t seed) { srand((unsigned)seed); }
int64_t kr_math_abs(int64_t x) { return x<0?-x:x; }
int64_t kr_math_min(int64_t a, int64_t b) { return a<b?a:b; }
int64_t kr_math_max(int64_t a, int64_t b) { return a>b?a:b; }
double kr_math_sqrt(double x) { return sqrt(x); }
double kr_math_floor(double x) { return floor(x); }
double kr_math_ceil(double x) { return ceil(x); }
double kr_math_round(double x) { return round(x); }
double kr_math_sin(double x) { return sin(x); }
double kr_math_cos(double x) { return cos(x); }
double kr_math_tan(double x) { return tan(x); }
double kr_math_pow(double x, double y) { return pow(x,y); }
void kr_log_debug(kr_str msg) { fprintf(stderr,"[DEBUG] %s\n",msg); }
void kr_log_info(kr_str msg) { fprintf(stderr,"[INFO] %s\n",msg); }
void kr_log_warn(kr_str msg) { fprintf(stderr,"[WARN] %s\n",msg); }
void kr_log_error(kr_str msg) { fprintf(stderr,"[ERROR] %s\n",msg); }
void kr_log_set_level(int64_t lvl) { (void)lvl; }
int64_t kr_bench_start() { return (int64_t)clock(); }
int64_t kr_bench_end(int64_t start, ...) { return (int64_t)clock() - start; }
int64_t kr_remove(kr_str path) { return (int64_t)remove(path); }
int64_t kr_rename(kr_str old, kr_str new_path) { return (int64_t)rename(old,new_path); }
void* kr_rand_bytes(int64_t n) { void* buf=malloc((size_t)n); for(int64_t i=0;i<n;i++)((char*)buf)[i]=(char)rand(); return buf; }
int64_t kr_bytes_eq(void* a, void* b, int64_t n) { return memcmp(a,b,(size_t)n)==0; }
void kr_println(kr_str s) { printf("%s\n",s); }
void* kr_mutex_new() { return malloc(64); }
void kr_mutex_free(void* m) { free(m); }
#define kr_channel_new(...) ((void*)0)
#define kr_channel_create(...) ((void*)0)
void kr_channel_send(void* ch, int64_t val) { (void)ch; (void)val; }
int64_t kr_channel_recv(void* ch) { (void)ch; return 0; }
int64_t kr_channel_try_send(void* ch, int64_t val) { (void)ch; (void)val; return 0; }
int64_t kr_channel_try_recv(void* ch) { (void)ch; return 0; }
void kr_channel_close(void* ch) { (void)ch; }
void* kr_condvar_create() { return malloc(64); }
void kr_condvar_destroy(void* cv) { free(cv); }
void kr_condvar_signal(void* cv) { (void)cv; }
void kr_condvar_broadcast(void* cv) { (void)cv; }
void* kr_pool_new(int64_t n) { (void)n; return malloc(8); }
void kr_pool_shutdown(void* p) { free(p); }
void* kr_executor_new() { return malloc(8); }
void kr_executor_run(void* e) { (void)e; }
void kr_executor_shutdown(void* e) { free(e); }
void* kr_cancel_token_new() { return calloc(1,sizeof(int64_t)); }
void kr_cancel_token_cancel(void* t) { *(int64_t*)t=1; }
int64_t kr_cancel_token_is_cancelled(void* t) { return *(int64_t*)t; }
void* kr_atomic_new(int64_t v) { int64_t* p=(int64_t*)malloc(sizeof(int64_t)); *p=v; return p; }
void kr_atomic_store(void* p, int64_t v) { *(int64_t*)p=v; }
int64_t kr_atomic_load(void* p) { return *(int64_t*)p; }
int64_t kr_atomic_add(void* p, int64_t v) { int64_t old=*(int64_t*)p; *(int64_t*)p=old+v; return old; }
int64_t kr_atomic_sub(void* p, int64_t v) { int64_t old=*(int64_t*)p; *(int64_t*)p=old-v; return old; }
int64_t kr_atomic_cas(void* p, int64_t expected, int64_t desired) { if(*(int64_t*)p==expected){*(int64_t*)p=desired; return 1;} return 0; }
double kr_kraken_sin(double x){ return sin(x); }
double kr_kraken_cos(double x){ return cos(x); }
double kr_kraken_tan(double x){ return tan(x); }
double kr_kraken_asin(double x){ return asin(x); }
double kr_kraken_acos(double x){ return acos(x); }
double kr_kraken_atan(double x){ return atan(x); }
double kr_kraken_atan2(double y,double x){ return atan2(y,x); }
double kr_kraken_sinh(double x){ return sinh(x); }
double kr_kraken_cosh(double x){ return cosh(x); }
double kr_kraken_tanh(double x){ return tanh(x); }
double kr_kraken_exp(double x){ return exp(x); }
double kr_kraken_log(double x){ return log(x); }
double kr_kraken_log10(double x){ return log10(x); }
double kr_kraken_log2(double x){ return log(x)/log(2.0); }
double kr_kraken_pow(double b,double e){ return pow(b,e); }
double kr_kraken_sqrt(double x){ return sqrt(x); }
double kr_kraken_cbrt(double x){ return cbrt(x); }
double kr_kraken_ceil(double x){ return ceil(x); }
double kr_kraken_floor(double x){ return floor(x); }
double kr_kraken_round(double x){ return round(x); }
double kr_kraken_trunc(double x){ return trunc(x); }
double kr_kraken_fmod(double x,double y){ return fmod(x,y); }
double kr_kraken_remainder(double x,double y){ return remainder(x,y); }
double kr_kraken_fabs(double x){ return fabs(x); }
double kr_kraken_hypot(double x,double y){ return hypot(x,y); }
int64_t kr_kraken_time(){ return (int64_t)time(NULL); }
int64_t kr_kraken_clock(){ return (int64_t)clock(); }
int64_t kr_kraken_clocks_per_sec(){ return (int64_t)CLOCKS_PER_SEC; }
double kr_kraken_difftime(int64_t t1,int64_t t0){ return difftime((time_t)t1,(time_t)t0); }
kr_str kr_kraken_strftime(kr_str fmt,int64_t ts){ static char b[128]; time_t t=(time_t)ts; struct tm* tmv=localtime(&t); if(!tmv)return ""; strftime(b,127,fmt,tmv); return b; }
void* kr_kraken_calloc(int64_t c,int64_t sz){ return calloc((size_t)c,(size_t)sz); }
void* kr_kraken_aligned_alloc(int64_t a,int64_t sz){ (void)a; return malloc((size_t)sz); }
void* kr_kraken_calloc_tracked(int64_t c,int64_t sz, ...){ return calloc((size_t)c,(size_t)sz); }
void* kr_kraken_malloc_tracked(int64_t sz, ...){ return malloc((size_t)sz); }
void* kr_kraken_realloc_tracked(void* p,int64_t sz, ...){ return realloc(p,(size_t)sz); }
void kr_kraken_free(void* p){ free(p); }
void kr_kraken_free_tracked(void* p){ free(p); }
int64_t kr_kraken_get_allocation_count(){ return 0; }
int64_t kr_kraken_get_allocated_bytes(){ return 0; }
void kr_kraken_print_allocation_stats(){}
int64_t kr_kraken_ffi_check_null(int64_t p, ...){ return p==0; }
int64_t kr_kraken_ffi_safe_malloc(int64_t sz){ return (int64_t)(intptr_t)malloc((size_t)sz); }
int64_t kr_kraken_bounds_check(int64_t idx,int64_t len, ...){ return idx>=0 && idx<len; }
int64_t kr_kraken_bounds_check_range(int64_t s0,int64_t e0,int64_t len, ...){ return s0>=0 && e0>=s0 && e0<=len; }
void* kr_kraken_range_iter(int64_t s0,int64_t e0, ...){ int64_t* p=(int64_t*)malloc(sizeof(int64_t)*2); p[0]=s0; p[1]=e0; return p; }
void kr_kraken_range_free(void* p){ free(p); }
int64_t kr_kraken_type_alignment(int64_t sz){ if(sz>=8)return 8; if(sz>=4)return 4; if(sz>=2)return 2; return 1; }
int64_t kr_kraken_align_offset(int64_t off,int64_t a){ int64_t m=off%a; return m==0?0:(a-m); }
int64_t kr_kraken_calculate_padding(int64_t off,int64_t a){ return kr_kraken_align_offset(off,a); }
kr_str kr_kraken_str_concat(kr_str a,kr_str b){ return kr_str_concat(a,b); }
int64_t kr_kraken_str_len(kr_str s){ return (int64_t)strlen(s); }
int64_t kr_kraken_str_contains(kr_str s,kr_str sub){ return strstr(s,sub)!=NULL; }
int64_t kr_kraken_str_starts_with(kr_str s,kr_str p){ return strncmp(s,p,strlen(p))==0; }
int64_t kr_kraken_str_ends_with(kr_str s,kr_str x){ size_t ls=strlen(s), lx=strlen(x); return lx<=ls && strcmp(s+ls-lx,x)==0; }
kr_str kr_kraken_str_replace(kr_str s,kr_str old,kr_str rep){ return kr_str_replace(s,old,rep); }
kr_str kr_kraken_str_to_lower(kr_str s){ return kr_str_to_lower(s); }
kr_str kr_kraken_str_to_upper(kr_str s){ return kr_str_to_upper(s); }
kr_str kr_kraken_str_trim(kr_str s){ return kr_str_trim(s); }
kr_str kr_kraken_str_substring(kr_str s,int64_t a,int64_t b){ return kr_str_slice(s,a,b); }
int64_t kr_kraken_vprintf(kr_str fmt, ...){ return (int64_t)printf("%s", fmt); }
int64_t kr_kraken_vsprintf(kr_str buf, kr_str fmt, ...){ return (int64_t)sprintf(buf, "%s", fmt); }
int64_t kr_kraken_union_create(int64_t tag, void* data, ...){ (void)data; int64_t* p=(int64_t*)malloc(sizeof(int64_t)); *p=tag; return (int64_t)(intptr_t)p; }
void kr_kraken_union_free(int64_t u){ free((void*)(intptr_t)u); }
int64_t kr_kraken_union_get_tag(int64_t u){ void* p=(void*)(intptr_t)u; return p?*(int64_t*)p:0; }
void kr_kraken_union_set_tag(int64_t u,int64_t t){ void* p=(void*)(intptr_t)u; if(p)*(int64_t*)p=t; }
int64_t kr_kraken_union_check_tag(int64_t u,int64_t t, ...){ void* p=(void*)(intptr_t)u; return p && *(int64_t*)p==t; }

/* Forward declarations */
typedef struct Container Container;
void kr_test_empty_closure();
void kr_test_empty_closure_with_return();
void kr_test_no_parameters_no_captures();
void kr_test_no_parameters_with_captures();
void kr_test_all_captures_no_parameters();
void kr_test_single_parameter_no_captures();
void kr_test_many_parameters_no_captures();
void kr_test_many_parameters_many_captures();
void kr_test_closure_returning_void();
void kr_test_closure_with_early_return();
void kr_test_closure_with_multiple_returns();
void kr_test_closure_immediately_invoked();
void kr_test_closure_in_expression();
void kr_test_closure_as_struct_field();
void kr_test_closure_in_tuple();
void kr_test_closure_with_complex_body();
void kr_test_closure_capturing_closure();
void kr_test_move_closure_empty();
void kr_test_move_closure_no_captures();
void kr_test_move_closure_with_captures();
void kr_test_closure_with_same_param_and_capture_names();
void kr_test_closure_capturing_literal();
void kr_test_closure_with_string_operations();
void kr_test_closure_with_array_operations();
void kr_test_closure_with_nested_blocks();
void kr_test_closure_with_break_continue();
void kr_test_closure_with_match();
void kr_test_closure_with_type_annotations();
void kr_test_closure_assigned_to_variable();
void kr_test_closure_passed_and_returned();
void kr_test_zero_sized_closure();
void kr_test_large_capture_list();
void kr_main();

struct Container {
void* f;
};


static int64_t _kr_cl_8(void*);
static int64_t _kr_cl_25(void*);
static int64_t _kr_cl_50(void*);
static int64_t _kr_cl_79(void*);
static int64_t _kr_cl_125(void*);
static int64_t _kr_cl_152(void*, int64_t);
static int64_t _kr_cl_182(void*, int64_t, int64_t, int64_t, int64_t, int64_t);
static int64_t _kr_cl_259(void*, int64_t, int64_t, int64_t);
static int64_t _kr_cl_317(void*);
static int64_t _kr_cl_348(void*, int64_t);
static kr_str _kr_cl_398(void*, int64_t);
static int64_t _kr_cl_472(void*, int64_t);
static int64_t _kr_cl_508(void*, int64_t);
static int64_t _kr_cl_553(void*, int64_t);
static int64_t _kr_cl_582(void*, int64_t);
static int64_t _kr_cl_597(void*, int64_t);
static int64_t _kr_cl_642(void*, int64_t);
static int64_t _kr_cl_714(void*, int64_t);
static int64_t _kr_cl_732(void*, int64_t);
static int64_t _kr_cl_768(void*);
static int64_t _kr_cl_786(void*, int64_t);
static int64_t _kr_cl_829(void*);
static int64_t _kr_cl_855(void*, int64_t);
static int64_t _kr_cl_887(void*);
static int64_t _kr_cl_916(void*);
static int64_t _kr_cl_956(void*);
static int64_t _kr_cl_1003(void*);
static int64_t _kr_cl_1045(void*);
static kr_str _kr_cl_1095(void*, int64_t);
static int64_t _kr_cl_1166(void*, int64_t);
static int64_t _kr_cl_1203(void*, int64_t);
static int64_t _kr_cl_1266(void*, int64_t);
static int64_t _kr_cl_1300(void*);
static int64_t _kr_cl_1367(void*);
#define v1 ((int64_t*)_env)[0]
#define kr_v1 ((int64_t*)_env)[0]
#define v2 ((int64_t*)_env)[1]
#define kr_v2 ((int64_t*)_env)[1]
#define v3 ((int64_t*)_env)[2]
#define kr_v3 ((int64_t*)_env)[2]
#define v4 ((int64_t*)_env)[3]
#define kr_v4 ((int64_t*)_env)[3]
#define v5 ((int64_t*)_env)[4]
#define kr_v5 ((int64_t*)_env)[4]
#define v6 ((int64_t*)_env)[5]
#define kr_v6 ((int64_t*)_env)[5]
#define v7 ((int64_t*)_env)[6]
#define kr_v7 ((int64_t*)_env)[6]
#define v8 ((int64_t*)_env)[7]
#define kr_v8 ((int64_t*)_env)[7]
#define v9 ((int64_t*)_env)[8]
#define kr_v9 ((int64_t*)_env)[8]
#define v10 ((int64_t*)_env)[9]
#define kr_v10 ((int64_t*)_env)[9]
static int64_t _kr_cl_1367(void* _env) {
    return _KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(v1, v2), v3), v4), v5), v6), v7), v8), v9), v10);
}
#undef v1
#undef kr_v1
#undef v2
#undef kr_v2
#undef v3
#undef kr_v3
#undef v4
#undef kr_v4
#undef v5
#undef kr_v5
#undef v6
#undef kr_v6
#undef v7
#undef kr_v7
#undef v8
#undef kr_v8
#undef v9
#undef kr_v9
#undef v10
#undef kr_v10

static int64_t _kr_cl_1300(void* _env) {
}

static int64_t _kr_cl_1266(void* _env, int64_t x) {
    return x * 2;
}

#define x ((int64_t*)_env)[0]
#define kr_x ((int64_t*)_env)[0]
static int64_t _kr_cl_1203(void* _env, int64_t y) {
    return _KR_ADD(x, y);
}
#undef x
#undef kr_x

static int64_t _kr_cl_1166(void* _env, int64_t x) {
    return x * 2;
}

static kr_str _kr_cl_1095(void* _env, int64_t y) {
    if (y == 0) {
        return "zero";
    }
    else if (y == 1) {
        return "one";
    }
    else if (1) {
        return "other";
    }
}

#define arr ((int64_t*)_env)[0]
#define kr_arr ((int64_t*)_env)[0]
static int64_t _kr_cl_1045(void* _env) {
    {
        __auto_type _kr_arr_1051 = arr;
        for (int64_t _kr_i_1051 = 0; _kr_i_1051 < kr_vec_int_len(_kr_arr_1051); _kr_i_1051++) {
            __auto_type i = kr_vec_int_get(_kr_arr_1051, _kr_i_1051);
            if (_KR_EQ(i % 2, 0)) {
                return i;
            }
        }
    }
    return -1;
}
#undef arr
#undef kr_arr

#define x ((int64_t*)_env)[0]
#define kr_x ((int64_t*)_env)[0]
static int64_t _kr_cl_1003(void* _env) {
    return 0;
    0;
    return x;
}
#undef x
#undef kr_x

#define arr ((int64_t*)_env)[0]
#define kr_arr ((int64_t*)_env)[0]
static int64_t _kr_cl_956(void* _env) {
    __auto_type total = 0;
    {
        __auto_type _kr_arr_967 = arr;
        for (int64_t _kr_i_967 = 0; _kr_i_967 < kr_vec_int_len(_kr_arr_967); _kr_i_967++) {
            __auto_type i = kr_vec_int_get(_kr_arr_967, _kr_i_967);
            total = _KR_ADD(total, i);
        }
    }
    return total;
}
#undef arr
#undef kr_arr

#define prefix ((int64_t*)_env)[0]
#define kr_prefix ((int64_t*)_env)[0]
#define suffix ((int64_t*)_env)[1]
#define kr_suffix ((int64_t*)_env)[1]
static int64_t _kr_cl_916(void* _env) {
    return _KR_ADD(_KR_ADD(_KR_ADD(prefix, ", "), suffix), "!");
}
#undef prefix
#undef kr_prefix
#undef suffix
#undef kr_suffix

static int64_t _kr_cl_887(void* _env) {
    return 42;
}

static int64_t _kr_cl_855(void* _env, int64_t x) {
    return x * 2;
}

#define x ((int64_t*)_env)[0]
#define kr_x ((int64_t*)_env)[0]
#define y ((int64_t*)_env)[1]
#define kr_y ((int64_t*)_env)[1]
static int64_t _kr_cl_829(void* _env) {
    return _KR_ADD(x, y);
}
#undef x
#undef kr_x
#undef y
#undef kr_y

static int64_t _kr_cl_786(void* _env, int64_t x) {
    return x * 2;
}

static int64_t _kr_cl_768(void* _env) {
}

#define inner ((int64_t*)_env)[0]
#define kr_inner ((int64_t*)_env)[0]
static int64_t _kr_cl_732(void* _env, int64_t y) {
    return _KR_ADD(((int64_t(*)(void*, int64_t))_KR_CL_FN(inner))(_KR_CL_ENV(inner), y), 1);
}
#undef inner
#undef kr_inner

static int64_t _kr_cl_714(void* _env, int64_t x) {
    return x * 2;
}

static int64_t _kr_cl_642(void* _env, int64_t x) {
    __auto_type a = x * 2;
    __auto_type b = _KR_ADD(a, 10);
    __auto_type c = b / 2;
    if (c > 10) {
        __auto_type d = c - 5;
        return d;
    }
    else {
        return c;
    }
}

static int64_t _kr_cl_597(void* _env, int64_t x) {
    return x * 2;
}

static int64_t _kr_cl_582(void* _env, int64_t x) {
    return _KR_ADD(x, 1);
}

static int64_t _kr_cl_553(void* _env, int64_t x) {
    return x * 2;
}

static int64_t _kr_cl_508(void* _env, int64_t y) {
    return y * 2;
}

static int64_t _kr_cl_472(void* _env, int64_t x) {
    return x * 2;
}

static kr_str _kr_cl_398(void* _env, int64_t x) {
    if (x < 0) {
        return "negative";
    }
    else     if (_KR_EQ(x, 0)) {
        return "zero";
    }
    else {
        return "positive";
    }
}

static int64_t _kr_cl_348(void* _env, int64_t x) {
    if (x < 0) {
        return 0;
    }
    return x;
}

#define side_effect ((int64_t*)_env)[0]
#define kr_side_effect ((int64_t*)_env)[0]
static int64_t _kr_cl_317(void* _env) {
    side_effect = _KR_ADD(side_effect, 1);
}
#undef side_effect
#undef kr_side_effect

#define x1 ((int64_t*)_env)[0]
#define kr_x1 ((int64_t*)_env)[0]
#define x2 ((int64_t*)_env)[1]
#define kr_x2 ((int64_t*)_env)[1]
#define x3 ((int64_t*)_env)[2]
#define kr_x3 ((int64_t*)_env)[2]
static int64_t _kr_cl_259(void* _env, int64_t a, int64_t b, int64_t c) {
    return _KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(x1, x2), x3), a), b), c);
}
#undef x1
#undef kr_x1
#undef x2
#undef kr_x2
#undef x3
#undef kr_x3

static int64_t _kr_cl_182(void* _env, int64_t a, int64_t b, int64_t c, int64_t d, int64_t e) {
    return _KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(a, b), c), d), e);
}

static int64_t _kr_cl_152(void* _env, int64_t x) {
    return x;
}

#define a ((int64_t*)_env)[0]
#define kr_a ((int64_t*)_env)[0]
#define b ((int64_t*)_env)[1]
#define kr_b ((int64_t*)_env)[1]
#define c ((int64_t*)_env)[2]
#define kr_c ((int64_t*)_env)[2]
#define d ((int64_t*)_env)[3]
#define kr_d ((int64_t*)_env)[3]
#define e ((int64_t*)_env)[4]
#define kr_e ((int64_t*)_env)[4]
static int64_t _kr_cl_125(void* _env) {
    return _KR_ADD(_KR_ADD(_KR_ADD(_KR_ADD(a, b), c), d), e);
}
#undef a
#undef kr_a
#undef b
#undef kr_b
#undef c
#undef kr_c
#undef d
#undef kr_d
#undef e
#undef kr_e

#define x ((int64_t*)_env)[0]
#define kr_x ((int64_t*)_env)[0]
#define y ((int64_t*)_env)[1]
#define kr_y ((int64_t*)_env)[1]
static int64_t _kr_cl_79(void* _env) {
    return _KR_ADD(x, y);
}
#undef x
#undef kr_x
#undef y
#undef kr_y

static int64_t _kr_cl_50(void* _env) {
    return 42;
}

static int64_t _kr_cl_25(void* _env) {
    return 0;
}

static int64_t _kr_cl_8(void* _env) {
}

int64_t kr_process(void* f, int64_t x);
int64_t kr_process(void* f, int64_t x) {
    return ((int64_t(*)(void*, int64_t))_KR_CL_FN(f))(_KR_CL_ENV(f), x);
}

void kr_test_empty_closure() {
    __auto_type empty = _kr_cl_alloc((void*)_kr_cl_8, 0);
    ((int64_t(*)(void*))_KR_CL_FN(empty))(_KR_CL_ENV(empty));
}

void kr_test_empty_closure_with_return() {
    __auto_type empty = _kr_cl_alloc((void*)_kr_cl_25, 0);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(empty))(_KR_CL_ENV(empty));
}

void kr_test_no_parameters_no_captures() {
    __auto_type constant = _kr_cl_alloc((void*)_kr_cl_50, 0);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(constant))(_KR_CL_ENV(constant));
}

void kr_test_no_parameters_with_captures() {
    __auto_type x = 10;
    __auto_type y = 20;
    __auto_type sum = _kr_cl_alloc((void*)_kr_cl_79, 2, (int64_t)x, (int64_t)y);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(sum))(_KR_CL_ENV(sum));
}

void kr_test_all_captures_no_parameters() {
    __auto_type a = 1;
    __auto_type b = 2;
    __auto_type c = 3;
    __auto_type d = 4;
    __auto_type e = 5;
    __auto_type sum_all = _kr_cl_alloc((void*)_kr_cl_125, 5, (int64_t)a, (int64_t)b, (int64_t)c, (int64_t)d, (int64_t)e);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(sum_all))(_KR_CL_ENV(sum_all));
}

void kr_test_single_parameter_no_captures() {
    __auto_type identity = _kr_cl_alloc((void*)_kr_cl_152, 0);
    __auto_type result = ((int64_t(*)(void*, int64_t))_KR_CL_FN(identity))(_KR_CL_ENV(identity), 42);
}

void kr_test_many_parameters_no_captures() {
    __auto_type sum5 = _kr_cl_alloc((void*)_kr_cl_182, 0);
    __auto_type result = ((int64_t(*)(void*, int64_t, int64_t, int64_t, int64_t, int64_t))_KR_CL_FN(sum5))(_KR_CL_ENV(sum5), 1, 2, 3, 4, 5);
}

void kr_test_many_parameters_many_captures() {
    __auto_type x1 = 1;
    __auto_type x2 = 2;
    __auto_type x3 = 3;
    __auto_type complex = _kr_cl_alloc((void*)_kr_cl_259, 3, (int64_t)x1, (int64_t)x2, (int64_t)x3);
    __auto_type result = ((int64_t(*)(void*, int64_t, int64_t, int64_t))_KR_CL_FN(complex))(_KR_CL_ENV(complex), 4, 5, 6);
}

void kr_test_closure_returning_void() {
    __auto_type side_effect = 0;
    __auto_type do_something = _kr_cl_alloc((void*)_kr_cl_317, 1, (int64_t)side_effect);
    ((int64_t(*)(void*))_KR_CL_FN(do_something))(_KR_CL_ENV(do_something));
    ((int64_t(*)(void*))_KR_CL_FN(do_something))(_KR_CL_ENV(do_something));
    ((int64_t(*)(void*))_KR_CL_FN(do_something))(_KR_CL_ENV(do_something));
}

void kr_test_closure_with_early_return() {
    __auto_type check = _kr_cl_alloc((void*)_kr_cl_348, 0);
    __auto_type r1 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(check))(_KR_CL_ENV(check), -5);
    __auto_type r2 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(check))(_KR_CL_ENV(check), 10);
}

void kr_test_closure_with_multiple_returns() {
    __auto_type classify = _kr_cl_alloc((void*)_kr_cl_398, 0);
    __auto_type r1 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(classify))(_KR_CL_ENV(classify), -5);
    __auto_type r2 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(classify))(_KR_CL_ENV(classify), 0);
    __auto_type r3 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(classify))(_KR_CL_ENV(classify), 10);
}

void kr_test_closure_immediately_invoked() {
    __auto_type result = _kr_cl_472(NULL, 21);
}

void kr_test_closure_in_expression() {
    __auto_type x = 10;
    __auto_type result = _KR_ADD(x, _kr_cl_508(NULL, 5));
}

void kr_test_closure_as_struct_field() {
    __auto_type c = (Container){.f = _kr_cl_alloc((void*)_kr_cl_553, 0)};
    __auto_type result = ((int64_t(*)(void*, int64_t))_KR_CL_FN(c.f))(_KR_CL_ENV(c.f), 21);
}

void kr_test_closure_in_tuple() {
    __auto_type t = (KrTuple2){.f0 = _kr_cl_alloc((void*)_kr_cl_582, 0), .f1 = _kr_cl_alloc((void*)_kr_cl_597, 0)};
    __auto_type r1 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(t.f0))(_KR_CL_ENV(t.f0), 5);
    __auto_type r2 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(t.f1))(_KR_CL_ENV(t.f1), 5);
}

void kr_test_closure_with_complex_body() {
    __auto_type complex = _kr_cl_alloc((void*)_kr_cl_642, 0);
    __auto_type result = ((int64_t(*)(void*, int64_t))_KR_CL_FN(complex))(_KR_CL_ENV(complex), 10);
}

void kr_test_closure_capturing_closure() {
    __auto_type inner = _kr_cl_alloc((void*)_kr_cl_714, 0);
    __auto_type outer = _kr_cl_alloc((void*)_kr_cl_732, 1, (int64_t)inner);
    __auto_type result = ((int64_t(*)(void*, int64_t))_KR_CL_FN(outer))(_KR_CL_ENV(outer), 5);
}

void kr_test_move_closure_empty() {
    __auto_type empty = _kr_cl_alloc((void*)_kr_cl_768, 0);
    ((int64_t(*)(void*))_KR_CL_FN(empty))(_KR_CL_ENV(empty));
}

void kr_test_move_closure_no_captures() {
    __auto_type f = _kr_cl_alloc((void*)_kr_cl_786, 0);
    __auto_type result = ((int64_t(*)(void*, int64_t))_KR_CL_FN(f))(_KR_CL_ENV(f), 21);
}

void kr_test_move_closure_with_captures() {
    __auto_type x = 10;
    __auto_type y = 20;
    __auto_type f = _kr_cl_alloc((void*)_kr_cl_829, 2, (int64_t)x, (int64_t)y);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(f))(_KR_CL_ENV(f));
}

void kr_test_closure_with_same_param_and_capture_names() {
    __auto_type x = 10;
    __auto_type f = _kr_cl_alloc((void*)_kr_cl_855, 0);
    __auto_type result = ((int64_t(*)(void*, int64_t))_KR_CL_FN(f))(_KR_CL_ENV(f), 5);
}

void kr_test_closure_capturing_literal() {
    __auto_type f = _kr_cl_alloc((void*)_kr_cl_887, 0);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(f))(_KR_CL_ENV(f));
}

void kr_test_closure_with_string_operations() {
    __auto_type prefix = "Hello";
    __auto_type suffix = "World";
    __auto_type concat = _kr_cl_alloc((void*)_kr_cl_916, 2, (int64_t)prefix, (int64_t)suffix);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(concat))(_KR_CL_ENV(concat));
}

void kr_test_closure_with_array_operations() {
    __auto_type arr = _kr_vec_int_of(5, (int64_t)1, (int64_t)2, (int64_t)3, (int64_t)4, (int64_t)5);
    __auto_type sum = _kr_cl_alloc((void*)_kr_cl_956, 1, (int64_t)arr);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(sum))(_KR_CL_ENV(sum));
}

void kr_test_closure_with_nested_blocks() {
    __auto_type x = 10;
    __auto_type f = _kr_cl_alloc((void*)_kr_cl_1003, 1, (int64_t)x);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(f))(_KR_CL_ENV(f));
}

void kr_test_closure_with_break_continue() {
    __auto_type arr = _kr_vec_int_of(5, (int64_t)1, (int64_t)2, (int64_t)3, (int64_t)4, (int64_t)5);
    __auto_type find_even = _kr_cl_alloc((void*)_kr_cl_1045, 1, (int64_t)arr);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(find_even))(_KR_CL_ENV(find_even));
}

void kr_test_closure_with_match() {
    __auto_type x = 5;
    __auto_type classify = _kr_cl_alloc((void*)_kr_cl_1095, 0);
    __auto_type r1 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(classify))(_KR_CL_ENV(classify), 0);
    __auto_type r2 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(classify))(_KR_CL_ENV(classify), 1);
    __auto_type r3 = ((int64_t(*)(void*, int64_t))_KR_CL_FN(classify))(_KR_CL_ENV(classify), 5);
}

void kr_test_closure_with_type_annotations() {
    void* f = (void*)(intptr_t)(_kr_cl_alloc((void*)_kr_cl_1166, 0));
    __auto_type result = ((int64_t(*)(void*, int64_t))_KR_CL_FN(f))(_KR_CL_ENV(f), 21);
}

void kr_test_closure_assigned_to_variable() {
    __auto_type x = 10;
    __auto_type f = _kr_cl_alloc((void*)_kr_cl_1203, 1, (int64_t)x);
    __auto_type g = f;
    __auto_type result = ((int64_t(*)(void*, int64_t))_KR_CL_FN(g))(_KR_CL_ENV(g), 5);
}

void kr_test_closure_passed_and_returned() {
    __auto_type double_val = _kr_cl_alloc((void*)_kr_cl_1266, 0);
    __auto_type result = kr_process(double_val, 21);
}

void kr_test_zero_sized_closure() {
    __auto_type f = _kr_cl_alloc((void*)_kr_cl_1300, 0);
    ((int64_t(*)(void*))_KR_CL_FN(f))(_KR_CL_ENV(f));
}

void kr_test_large_capture_list() {
    __auto_type v1 = 1;
    __auto_type v2 = 2;
    __auto_type v3 = 3;
    __auto_type v4 = 4;
    __auto_type v5 = 5;
    __auto_type v6 = 6;
    __auto_type v7 = 7;
    __auto_type v8 = 8;
    __auto_type v9 = 9;
    __auto_type v10 = 10;
    __auto_type sum_all = _kr_cl_alloc((void*)_kr_cl_1367, 10, (int64_t)v1, (int64_t)v2, (int64_t)v3, (int64_t)v4, (int64_t)v5, (int64_t)v6, (int64_t)v7, (int64_t)v8, (int64_t)v9, (int64_t)v10);
    __auto_type result = ((int64_t(*)(void*))_KR_CL_FN(sum_all))(_KR_CL_ENV(sum_all));
}

void kr_main() {
    kr_test_empty_closure();
    kr_test_empty_closure_with_return();
    kr_test_no_parameters_no_captures();
    kr_test_no_parameters_with_captures();
    kr_test_all_captures_no_parameters();
    kr_test_single_parameter_no_captures();
    kr_test_many_parameters_no_captures();
    kr_test_many_parameters_many_captures();
    kr_test_closure_returning_void();
    kr_test_closure_with_early_return();
    kr_test_closure_with_multiple_returns();
    kr_test_closure_immediately_invoked();
    kr_test_closure_in_expression();
    kr_test_closure_as_struct_field();
    kr_test_closure_in_tuple();
    kr_test_closure_with_complex_body();
    kr_test_closure_capturing_closure();
    kr_test_move_closure_empty();
    kr_test_move_closure_no_captures();
    kr_test_move_closure_with_captures();
    kr_test_closure_with_same_param_and_capture_names();
    kr_test_closure_capturing_literal();
    kr_test_closure_with_string_operations();
    kr_test_closure_with_array_operations();
    kr_test_closure_with_nested_blocks();
    kr_test_closure_with_break_continue();
    kr_test_closure_with_match();
    kr_test_closure_with_type_annotations();
    kr_test_closure_assigned_to_variable();
    kr_test_closure_passed_and_returned();
    kr_test_zero_sized_closure();
    kr_test_large_capture_list();
}


int main(int argc, char* argv[]) {
    kr_main();
    return 0;
}
