// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
typedef struct Container Container;
void kr_test_empty_closure();
void kr_test_empty_closure_with_return();
void kr_test_no_parameters_no_captures();
void kr_test_no_parameters_with_captures();
void kr_test_all_captures_no_parameters();
void kr_test_single_parameter_no_captures();
void kr_test_many_parameters_no_captures();
void kr_test_many_parameters_many_captures();
void kr_test_closure_returning_void();
void kr_test_closure_with_early_return();
void kr_test_closure_with_multiple_returns();
void kr_test_closure_immediately_invoked();
void kr_test_closure_in_expression();
void kr_test_closure_as_struct_field();
void kr_test_closure_in_tuple();
void kr_test_closure_with_complex_body();
void kr_test_closure_capturing_closure();
void kr_test_move_closure_empty();
void kr_test_move_closure_no_captures();
void kr_test_move_closure_with_captures();
void kr_test_closure_with_same_param_and_capture_names();
void kr_test_closure_capturing_literal();
void kr_test_closure_with_string_operations();
void kr_test_closure_with_array_operations();
void kr_test_closure_with_nested_blocks();
void kr_test_closure_with_break_continue();
void kr_test_closure_with_match();
void kr_test_closure_with_type_annotations();
void kr_test_closure_assigned_to_variable();
void kr_test_closure_passed_and_returned();
void kr_test_zero_sized_closure();
void kr_test_large_capture_list();
void kr_main();

struct Container {
void* f;
void* (;
void* ->;
};

void kr_test_empty_closure() {
    __auto_type empty = ||;
    {;
}

void kr_test_empty_closure_with_return() {
    __auto_type empty = ||;
    ->;
    int;
    {;
    return 0;
}

void kr_test_no_parameters_no_captures() {
    __auto_type constant = ||;
    42;
    __auto_type result = kr_constant();
}

void kr_test_no_parameters_with_captures() {
    __auto_type x = 10;
    __auto_type y = 20;
    __auto_type sum = ||;
    x + y;
    __auto_type result = kr_sum();
}

void kr_test_all_captures_no_parameters() {
    __auto_type a = 1;
    __auto_type b = 2;
    __auto_type c = 3;
    __auto_type d = 4;
    __auto_type e = 5;
    __auto_type sum_all = ||;
    a + b + c + d + e;
    __auto_type result = kr_sum_all();
}

void kr_test_single_parameter_no_captures() {
    __auto_type identity = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x;
}

void kr_test_many_parameters_no_captures() {
    __auto_type sum5 = |;
    a;
    :;
    int;
    ,;
    b;
    :;
    int;
    ,;
    c;
    :;
    int;
    ,;
    d;
    :;
    int;
    ,;
    e;
    :;
    int | ->;
    int;
    {;
    return a + b + c + d + e;
}

void kr_test_many_parameters_many_captures() {
    __auto_type x1 = 1;
    __auto_type x2 = 2;
    __auto_type x3 = 3;
    __auto_type complex = |;
    a;
    :;
    int;
    ,;
    b;
    :;
    int;
    ,;
    c;
    :;
    int | ->;
    int;
    {;
    return x1 + x2 + x3 + a + b + c;
}

void kr_test_closure_returning_void() {
    int64_t mut;
    side_effect = 0;
    __auto_type do_something = ||;
    {;
    side_effect = side_effect + 1;
}

void kr_test_closure_with_early_return() {
    __auto_type check = |;
    x;
    :;
    int | ->;
    int;
    {;
    if (x < 0) {
        return 0;
    }
    return x;
}

void kr_test_closure_with_multiple_returns() {
    __auto_type classify = |;
    x;
    :;
    int | ->;
    string;
    {;
    if (x < 0) {
        return "negative";
    }
    else     if (_KR_EQ(x, 0)) {
        return "zero";
    }
    else {
        return "positive";
    }
}

void kr_test_closure_immediately_invoked() {
    __auto_type result = (|);
    x;
    :;
    int | ->;
    int;
    {;
    return x * 2;
}

void kr_test_closure_in_expression() {
    __auto_type x = 10;
    __auto_type result = x + (|);
    y;
    :;
    int | ->;
    int;
    {;
    return y * 2;
}

void kr_test_closure_as_struct_field() {
    struct;
    (Container){.f = fn(int), .int = }, .c = (Container){.f = |, .| = *, ., = ;, .result = c.f(21)}, .test_closure_in_tuple = ), .let = =(|, :, |, int, return, +, ;, , | x, int | ->, {, x * 2, }), .let = =, .. = (5), .let = =, .. = (5)};
    fn;
    kr_test_closure_with_complex_body();
    {;
    __auto_type complex = |;
    x;
    :;
    int | ->;
    int;
    {;
    __auto_type a = x * 2;
    __auto_type b = a + 10;
    __auto_type c = b / 2;
    if (c > 10) {
        __auto_type d = c - 5;
        return d;
    }
    else {
        return c;
    }
}

void kr_test_closure_capturing_closure() {
    __auto_type inner = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x * 2;
}

void kr_test_move_closure_empty() {
    __auto_type empty = move || {;
}

void kr_test_move_closure_no_captures() {
    __auto_type f = move | x;
    :;
    int | ->;
    int;
    {;
    return x * 2;
}

void kr_test_move_closure_with_captures() {
    __auto_type x = 10;
    __auto_type y = 20;
    __auto_type f = move || x + y;
    __auto_type result = kr_f();
}

void kr_test_closure_with_same_param_and_capture_names() {
    __auto_type x = 10;
    __auto_type f = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x * 2;
}

void kr_test_closure_capturing_literal() {
    __auto_type f = ||;
    42;
    __auto_type result = kr_f();
}

void kr_test_closure_with_string_operations() {
    __auto_type prefix = "Hello";
    __auto_type suffix = "World";
    __auto_type concat = ||;
    prefix + ", " + suffix + "!";
    __auto_type result = kr_concat();
}

void kr_test_closure_with_array_operations() {
    __auto_type arr = [;
    1;
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ];
    __auto_type sum = ||;
    {;
    __auto_type total = 0;
    for (i; arr; {) {
        total + i;
    }
    return total;
}

void kr_test_closure_with_nested_blocks() {
    __auto_type x = 10;
    __auto_type f = ||;
    {;
    {;
    {;
    return x;
}

void kr_test_closure_with_break_continue() {
    __auto_type arr = [;
    1;
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ];
    __auto_type find_even = ||;
    {;
    for (i; arr; {) {
        _KR_EQ(i % 2, 0);
        );
        {;
        return i;
    }
}

void kr_test_closure_with_match() {
    __auto_type x = 5;
    __auto_type classify = |;
    y;
    :;
    int | ->;
    string;
    {;
    if (y == 0) {
        = > "zero";
        ,;
        1 = >;
        "one";
        ,;
        _ = >;
        "other";
        ,;
    }
    __auto_type r1 = kr_classify(0);
    __auto_type r2 = kr_classify(1);
    __auto_type r3 = kr_classify(5);
}

void kr_test_closure_with_type_annotations() {
    void* f;
    (int);
    ->;
    int = |;
    x;
    :;
    int | ->;
    int;
    {;
    return x * 2;
}

void kr_test_closure_assigned_to_variable() {
    __auto_type x = 10;
    __auto_type f = |;
    y;
    :;
    int | ->;
    int;
    {;
    return x + y;
}

void kr_test_closure_passed_and_returned() {
    fn;
    kr_process(f, fn(int), int, x, int);
    ->;
    int;
    {;
    return kr_f(x);
}

void kr_test_zero_sized_closure() {
    __auto_type f = ||;
    {;
}

void kr_test_large_capture_list() {
    __auto_type v1 = 1;
    __auto_type v2 = 2;
    __auto_type v3 = 3;
    __auto_type v4 = 4;
    __auto_type v5 = 5;
    __auto_type v6 = 6;
    __auto_type v7 = 7;
    __auto_type v8 = 8;
    __auto_type v9 = 9;
    __auto_type v10 = 10;
    __auto_type sum_all = ||;
    v1 + v2 + v3 + v4 + v5 + v6 + v7 + v8 + v9 + v10;
    __auto_type result = kr_sum_all();
}

void kr_main() {
    kr_test_empty_closure();
    kr_test_empty_closure_with_return();
    kr_test_no_parameters_no_captures();
    kr_test_no_parameters_with_captures();
    kr_test_all_captures_no_parameters();
    kr_test_single_parameter_no_captures();
    kr_test_many_parameters_no_captures();
    kr_test_many_parameters_many_captures();
    kr_test_closure_returning_void();
    kr_test_closure_with_early_return();
    kr_test_closure_with_multiple_returns();
    kr_test_closure_immediately_invoked();
    kr_test_closure_in_expression();
    kr_test_closure_as_struct_field();
    kr_test_closure_in_tuple();
    kr_test_closure_with_complex_body();
    kr_test_closure_capturing_closure();
    kr_test_move_closure_empty();
    kr_test_move_closure_no_captures();
    kr_test_move_closure_with_captures();
    kr_test_closure_with_same_param_and_capture_names();
    kr_test_closure_capturing_literal();
    kr_test_closure_with_string_operations();
    kr_test_closure_with_array_operations();
    kr_test_closure_with_nested_blocks();
    kr_test_closure_with_break_continue();
    kr_test_closure_with_match();
    kr_test_closure_with_type_annotations();
    kr_test_closure_assigned_to_variable();
    kr_test_closure_passed_and_returned();
    kr_test_zero_sized_closure();
    kr_test_large_capture_list();
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
