// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
void kr_test_simple_nested();
void kr_test_double_nested();
void kr_test_nested_with_captures();
void kr_test_nested_closure_chain();
void kr_test_nested_with_state();
void kr_test_nested_returning_multiple();
void kr_test_nested_in_loop();
void kr_test_nested_conditional();
void kr_test_nested_recursive_style();
void kr_test_triple_nested();
void kr_test_nested_with_mixed_captures();
void kr_test_nested_closure_composition();
void kr_test_nested_partial_application();
void kr_test_deeply_nested_captures();
void kr_test_nested_with_parameters_and_captures();
void kr_main();

void kr_test_simple_nested() {
    __auto_type outer = |;
    x;
    :;
    int | ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    y | x + y;
}

void kr_test_double_nested() {
    __auto_type outer = |;
    x;
    :;
    int | ->;
    fn(int);
    ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    y | {;
    return |;
    z | x + y + z;
}

void kr_test_nested_with_captures() {
    __auto_type a = 10;
    __auto_type outer = |;
    b;
    :;
    int | ->;
    fn(int);
    ->;
    int;
    {;
    __auto_type inner = |;
    c;
    :;
    int | ->;
    int;
    {;
    return a + b + c;
}

void kr_test_nested_closure_chain() {
    __auto_type make_multiplier = |;
    factor;
    :;
    int | ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    x | {;
    __auto_type double = |;
    y;
    :;
    int | ->;
    int;
    {;
    return y * 2;
}

void kr_test_nested_with_state() {
    __auto_type make_counter = ||;
    ->;
    fn();
    ->;
    int;
    {;
    int64_t mut;
    count = 0;
    return ||;
    {;
    count = count + 1;
    return count;
}

void kr_test_nested_returning_multiple() {
    __auto_type make_ops = |;
    x;
    :;
    int | ->(fn(int), int, fn(int), int);
    {;
    __auto_type add = |;
    y;
    :;
    int | ->;
    int;
    {;
    return x + y;
}

void kr_test_nested_in_loop() {
    void* closures;
    fn(int);
    ->;
    int;
    ] = [;
    ];
    for (i; [; ,) {
        3;
        ,;
        4;
        ,;
        5;
        ];
        );
        {;
        __auto_type closure = |;
        x;
        :;
        int | ->;
        int;
        {;
        return x * i;
    }
    closures.push(closure);
}

void kr_test_nested_conditional() {
    __auto_type make_conditional = |;
    flag;
    :;
    bool | ->;
    fn(int);
    ->;
    int;
    {;
    if (flag) {
        return |;
        x | x * 2;
    }
    else {
        return |;
        x | x + 2;
    }
}

void kr_test_nested_recursive_style() {
    __auto_type make_factorial = ||;
    ->;
    fn(int);
    ->;
    int;
    {;
    __auto_type factorial = |;
    n;
    :;
    int | ->;
    int;
    {;
    if (n <= 1) {
        return 1;
    }
    else {
        return n;
    }
}

void kr_test_triple_nested() {
    __auto_type level1 = |;
    a;
    :;
    int | ->;
    fn(int);
    ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    b | {;
    return |;
    c | {;
    return a + b + c;
}

void kr_test_nested_with_mixed_captures() {
    __auto_type global = 100;
    __auto_type outer = |;
    x;
    :;
    int | ->;
    fn(int);
    ->;
    int;
    {;
    __auto_type local = 10;
    return |;
    y | global + x + local + y;
}

void kr_test_nested_closure_composition() {
    __auto_type compose = |;
    f;
    :;
    fn(int);
    ->;
    int;
    ,;
    g;
    :;
    fn(int);
    ->;
    int | ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    x | kr_f(kr_g(x));
}

void kr_test_nested_partial_application() {
    __auto_type add = |;
    x;
    :;
    int | ->;
    fn(int);
    ->;
    int;
    {;
    return |;
    y | x + y;
}

void kr_test_deeply_nested_captures() {
    __auto_type a = 1;
    __auto_type f1 = ||;
    {;
    __auto_type b = 2;
    __auto_type f2 = ||;
    {;
    __auto_type c = 3;
    __auto_type f3 = ||;
    {;
    __auto_type d = 4;
    __auto_type f4 = ||;
    {;
    return a + b + c + d;
}

void kr_test_nested_with_parameters_and_captures() {
    __auto_type multiplier = 3;
    __auto_type outer = |;
    x;
    :;
    int | ->;
    fn(int);
    ->;
    int;
    {;
    __auto_type offset = 10;
    return |;
    y | (x + y + offset) * multiplier;
}

void kr_main() {
    kr_test_simple_nested();
    kr_test_double_nested();
    kr_test_nested_with_captures();
    kr_test_nested_closure_chain();
    kr_test_nested_with_state();
    kr_test_nested_returning_multiple();
    kr_test_nested_in_loop();
    kr_test_nested_conditional();
    kr_test_nested_recursive_style();
    kr_test_triple_nested();
    kr_test_nested_with_mixed_captures();
    kr_test_nested_closure_composition();
    kr_test_nested_partial_application();
    kr_test_deeply_nested_captures();
    kr_test_nested_with_parameters_and_captures();
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
