// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
int64_t kr_test_tuple_edge_cases();
int64_t kr_test_destructuring_edge_cases();
int64_t kr_test_pattern_matching_edge_cases();
int64_t kr_main();

int64_t kr_test_tuple_edge_cases() {
    kr_test_section("Tuple Edge Cases");
    void* unit;
    ) = ());
    kr_test_pass("Empty tuple (unit type)");
    void* pair;
    int;
    ,;
    int;
    ) = (42);
    ,;
    43;
    );
    kr_assert_eq(pair.0, 42);
    kr_assert_eq(pair.1, 43);
    kr_test_pass("Two element tuple");
    void* large;
    int;
    ,;
    int;
    ,;
    int;
    ,;
    int;
    ,;
    int;
    ,;
    int;
    ,;
    int;
    ,;
    int;
    ,;
    int;
    ,;
    int;
    ) = (1);
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ,;
    6;
    ,;
    7;
    ,;
    8;
    ,;
    9;
    ,;
    10;
    );
    kr_assert_eq(large.0, 1);
    kr_assert_eq(large.5, 6);
    kr_assert_eq(large.9, 10);
    kr_test_pass("Large tuple (10 elements)");
    void* nested;
    (int);
    ,;
    int;
    );
    ,(int, int);
    ) = ((1));
    ,;
    2;
    );
    ,(3, 4);
    );
    void* first;
    int;
    ,;
    int;
    ) = nested.0;
    void* second;
    int;
    ,;
    int;
    ) = nested.1;
    kr_assert_eq(first.0, 1);
    kr_assert_eq(first.1, 2);
    kr_assert_eq(second.0, 3);
    kr_assert_eq(second.1, 4);
    kr_test_pass("Deeply nested tuples");
    void* triple;
    ((int));
    ,;
    int;
    );
    ,;
    int;
    );
    ,;
    int;
    ) = (((1)));
    ,;
    2;
    );
    ,;
    3;
    );
    ,;
    4;
    );
    void* outer;
    (int);
    ,;
    int;
    );
    ,;
    int;
    ) = triple.0;
    void* inner;
    int;
    ,;
    int;
    ) = outer.0;
    kr_assert_eq(inner.0, 1);
    kr_assert_eq(inner.1, 2);
    kr_assert_eq(outer.1, 3);
    kr_assert_eq(triple.1, 4);
    kr_test_pass("Triple nested tuples");
    void* same;
    int;
    ,;
    int;
    ,;
    int;
    ) = (5);
    ,;
    5;
    ,;
    5;
    );
    kr_assert_eq(same.0, 5);
    kr_assert_eq(same.1, 5);
    kr_assert_eq(same.2, 5);
    kr_test_pass("Tuple with identical values");
    void* with_zero;
    int;
    ,;
    int;
    ,;
    int;
    ) = (0);
    ,;
    1;
    ,;
    0;
    );
    kr_assert_eq(with_zero.0, 0);
    kr_assert_eq(with_zero.1, 1);
    kr_assert_eq(with_zero.2, 0);
    kr_test_pass("Tuple with zero values");
    void* negative;
    int;
    ,;
    int;
    ) = (-1);
    , - 100;
    );
    kr_assert_eq(negative.0, -1);
    kr_assert_eq(negative.1, -100);
    kr_test_pass("Tuple with negative numbers");
    0;
}

int64_t kr_test_destructuring_edge_cases() {
    kr_test_section("Destructuring Edge Cases");
    int64_t (;
    );
    :() = ());
    kr_test_pass("Destructure empty tuple");
    int64_t (;
    x;
    ,;
    y;
    );
    :(int, int) = (99);
    ,;
    100;
    );
    kr_assert_eq(x, 99);
    kr_assert_eq(y, 100);
    kr_test_pass("Destructure two element tuple");
    int64_t (;
    a;
    ,;
    _;
    ,;
    c;
    );
    :(int, int, int) = (1);
    ,;
    2;
    ,;
    3;
    );
    kr_assert_eq(a, 1);
    kr_assert_eq(c, 3);
    kr_test_pass("Destructure with wildcards");
    int64_t (;
    _;
    ,;
    _;
    ,;
    _;
    );
    :(int, int, int) = (10);
    ,;
    20;
    ,;
    30;
    );
    kr_test_pass("Destructure all wildcards");
    int64_t (;
    v1;
    ,;
    v2;
    ,;
    v3;
    ,;
    v4;
    ,;
    v5;
    ,;
    v6;
    ,;
    v7;
    ,;
    v8;
    );
    :(int, int, int, int, int, int, int, int) = (1);
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ,;
    6;
    ,;
    7;
    ,;
    8;
    );
    kr_assert_eq(v1, 1);
    kr_assert_eq(v4, 4);
    kr_assert_eq(v8, 8);
    kr_test_pass("Destructure large tuple");
    int64_t (;
    (p);
    ,;
    q;
    );
    ,;
    r;
    );
    :((int), int);
    ,;
    int;
    ) = ((10));
    ,;
    20;
    );
    ,;
    30;
    );
    kr_assert_eq(p, 10);
    kr_assert_eq(q, 20);
    kr_assert_eq(r, 30);
    kr_test_pass("Destructure nested tuple");
    int64_t (;
    x;
    ,;
    y;
    );
    :(int, int) = (1);
    ,;
    2;
    );
    kr_assert_eq(x, 1);
    kr_assert_eq(y, 2);
    int64_t (;
    x;
    ,;
    y;
    );
    :(int, int) = (3);
    ,;
    4;
    );
    kr_assert_eq(x, 3);
    kr_assert_eq(y, 4);
    kr_test_pass("Destructure with shadowing");
    int64_t (;
    z1;
    ,;
    z2;
    );
    :(int, int) = (0);
    ,;
    0;
    );
    kr_assert_eq(z1, 0);
    kr_assert_eq(z2, 0);
    kr_test_pass("Destructure zero values");
    0;
}

int64_t kr_test_pattern_matching_edge_cases() {
    kr_test_section("Pattern Matching Edge Cases");
    void* unit;
    ) = ());
    if (unit == () {
        );
        ->;
        {;
        kr_test_pass("Match empty tuple");
    }
    void* pair;
    int;
    ,;
    int;
    ) = (42);
    ,;
    43;
    );
    if (pair == () {
        x;
        ,;
        y;
        );
        ->;
        {;
        kr_assert_eq(x, 42);
        kr_assert_eq(y, 43);
        kr_test_pass("Match two element tuple");
    }
    void* triple;
    int;
    ,;
    int;
    ,;
    int;
    ) = (1);
    ,;
    2;
    ,;
    3;
    );
    if (triple == () {
        _;
        ,;
        _;
        ,;
        _;
        );
        ->;
        {;
        kr_test_pass("Match with all wildcards");
    }
    void* mixed;
    int;
    ,;
    int;
    ,;
    int;
    ) = (5);
    ,;
    10;
    ,;
    15;
    );
    if (mixed == () {
        a;
        ,;
        _;
        ,;
        c;
        );
        ->;
        {;
        kr_assert_eq(a, 5);
        kr_assert_eq(c, 15);
        kr_test_pass("Match with mixed wildcards and bindings");
    }
    void* nested;
    (int);
    ,;
    int;
    );
    ,;
    int;
    ) = ((7));
    ,;
    8;
    );
    ,;
    9;
    );
    if (nested == () {
        (x);
        ,;
        y;
        );
        ,;
        z;
        );
        ->;
        {;
        kr_assert_eq(x, 7);
        kr_assert_eq(y, 8);
        kr_assert_eq(z, 9);
        kr_test_pass("Match nested tuple");
    }
    void* zeros;
    int;
    ,;
    int;
    ) = (0);
    ,;
    0;
    );
    if (zeros == () {
        a;
        ,;
        b;
        );
        ->;
        {;
        kr_assert_eq(a, 0);
        kr_assert_eq(b, 0);
        kr_test_pass("Match tuple with zeros");
    }
    void* negs;
    int;
    ,;
    int;
    ) = (-5);
    , - 10;
    );
    if (negs == () {
        x;
        ,;
        y;
        );
        ->;
        {;
        kr_assert_eq(x, -5);
        kr_assert_eq(y, -10);
        kr_test_pass("Match tuple with negatives");
    }
    void* large;
    int;
    ,;
    int;
    ,;
    int;
    ,;
    int;
    ,;
    int;
    ) = (1);
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    );
    if (large == () {
        a;
        ,;
        b;
        ,;
        c;
        ,;
        d;
        ,;
        e;
        );
        ->;
        {;
        kr_assert_eq(a, 1);
        kr_assert_eq(c, 3);
        kr_assert_eq(e, 5);
        kr_test_pass("Match large tuple");
    }
    void* t1;
    int;
    ,;
    int;
    ) = (10);
    ,;
    20;
    );
    int64_t (;
    a;
    ,;
    b;
    );
    :(int, int) = t1;
    void* t2;
    int;
    ,;
    int;
    ) = (a);
    ,;
    b;
    );
    int64_t (;
    c;
    ,;
    d;
    );
    :(int, int) = t2;
    kr_assert_eq(c, 10);
    kr_assert_eq(d, 20);
    kr_test_pass("Multiple sequential destructurings");
    void* big_tuple;
    (int);
    ,;
    int;
    );
    ,(int, int);
    ) = ((1));
    ,;
    2;
    );
    ,(3, 4);
    );
    int64_t (;
    first;
    ,;
    second;
    );
    :((int), int);
    ,(int, int);
    ) = big_tuple;
    if (first == () {
        x;
        ,;
        y;
        );
        ->;
        {;
        kr_assert_eq(x, 1);
        kr_assert_eq(y, 2);
    }
    if (second == () {
        x;
        ,;
        y;
        );
        ->;
        {;
        kr_assert_eq(x, 3);
        kr_assert_eq(y, 4);
    }
    kr_test_pass("Destructure then match");
    0;
}

int64_t kr_main() {
    kr_puts("=== COMPREHENSIVE EDGE CASE TESTING ===");
    kr_puts("");
    kr_test_tuple_edge_cases();
    kr_test_destructuring_edge_cases();
    kr_test_pattern_matching_edge_cases();
    kr_puts("");
    kr_puts("=== ALL EDGE CASE TESTS PASSED ===");
    0;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
