// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
void* kr_map(U T, void* (, void* T, void* :, U ));
void kr_test_map_basic();
void kr_test_map_transform();
U kr_filter(void* T, T :, void* ,, void* (, void* bool, void* T, void* result, void* ], item ;, void* arr, void* (, push result, void* item, result }, test_filter_basic }, void* ), void* =, void* 2, void* 4, void* 6, filter evens, void* numbers, void* |, void* ==, test_filter_strings }, void* ), void* =, void* world, void* hi, filter long_words, void* words, void* |, void* (, void* ), T fold, void* U, T :, void* ,, void* ,, void* (, U ));
void kr_test_fold_sum();
void kr_test_fold_product();
void kr_test_fold_string_concat();
void kr_test_chain_map_filter();
void kr_test_chain_filter_map_fold();
void kr_zip(U T, void* (, void* T, U :, void* ), U T);
void kr_test_zip_basic();
void kr_test_closure_capture_generic();
void kr_test_closure_capture_multiple();
T kr_make_adder(void* T, void* :, T fn);
void kr_test_make_adder();
void kr_test_make_adder_with_map();
void kr_flat_map(U T, void* (, void* T, void* :, void* ), void* ], void* U, void* result, void* ], item ;, void* arr, void* =, void* ), void* in, void* ., void* ), void* return, void* fn);
void kr_partition(void* T, T :, void* ,, void* (, void* bool, void* [, void* [);
void kr_test_partition();
void kr_test_move_closure_generic();
void kr_test_inference_from_return();
void kr_test_inference_from_argument();
void kr_test_inference_nested();
void kr_main();

void* kr_map(U T, void* (, void* T, void* :, U )) {
    ];
    {;
    void* result;
    U;
    ] = [;
    ];
    for (in; {; .) {
        kr_f(item);
        );
    }
    return result;
}

void kr_test_map_basic() {
    __auto_type numbers = [;
    1;
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ];
    __auto_type doubled = kr_map(numbers, |, |, *, ), }, kr_test_map_transform(), let, =[1], ,, ], let, =, (numbers), |, |, +, ., ()), }, filter < T > (arr), [, ], predicate, fn(T), bool);
    ->[T];
    {;
    void* result;
    T;
    ] = [;
    ];
    for (in; {; kr_predicate(item)) {
        .;
        kr_push(item);
    }
}

void kr_test_filter_basic() {
    __auto_type numbers = [;
    1;
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ,;
    6;
    ];
    __auto_type evens = kr_filter(numbers, |, |, _KR_EQ(%, ==), ), }, kr_test_filter_strings(), let, =["hello"], ,, ,, ], let, =, (words), |, |, ., () > 3), }, fold < T, U > (arr), [, ], init, U, f, fn(U, T), U);
    ->;
    (U){.let = =, .; = item, .arr = acc, .f = acc, .item = ;};
    return acc;
}

void kr_test_fold_sum() {
    __auto_type numbers = [;
    1;
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ];
    __auto_type sum = kr_fold(numbers, 0, |, ,, |, +, ), }, kr_test_fold_product(), let, =[1], ,, ,, ], let, =, (numbers), 1, |, ,, |, *, ), }, kr_test_fold_string_concat(), let, =["Hello"], ,, ], let, =, (words), "", |, ,, |, +, ), }, kr_test_chain_map_filter(), let, =[1], ,, ,, ,, ,, ,, ,, ,, ,, ], let, =, (numbers), |, |, *, ), let, =, (squared), |, |, _KR_EQ(%, ==), ), }, kr_test_chain_filter_map_fold(), let, =[1], ,, ,, ,, ,, ], let, =, (numbers), |, |, _KR_EQ(%, ==), ), let, =, (evens), |, |, *, ), let, =, (doubled), 0, |, ,, |, +, ), }, zip < T, U > (arr1), [, ], arr2, [, ]);
    ->[(T)];
    U;
    );
    ];
    {;
    void* result;
    (T);
    ,;
    U;
    );
    ] = [;
    ];
    __auto_type len = if;
    arr1.len() < arr2.len();
    {;
    arr1.len();
}

void kr_test_zip_basic() {
    __auto_type numbers = [;
    1;
    ,;
    2;
    ,;
    3;
    ];
    __auto_type letters = [;
    "a";
    ,;
    "b";
    ,;
    "c";
    ];
    __auto_type pairs = kr_zip(numbers, letters);
}

void kr_test_closure_capture_generic() {
    __auto_type multiplier = 3;
    __auto_type numbers = [;
    1;
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ];
    __auto_type result = kr_map(numbers, |, |, *, ), }, kr_test_closure_capture_multiple(), let, =, ;, scale, 2, let, =[1], ,, ], let, =, (numbers), |, |(x * scale) + offset);
}

T kr_make_adder(void* T, void* :, T fn) {
    return |;
    x | x + n;
}

void kr_test_make_adder() {
    __auto_type add5 = kr_make_adder(5);
    __auto_type result = kr_add5(10);
}

void kr_test_make_adder_with_map() {
    __auto_type add10 = kr_make_adder(10);
    __auto_type numbers = [;
    1;
    ,;
    2;
    ,;
    3;
    ];
    __auto_type result = kr_map(numbers, add10);
}

void kr_flat_map(U T, void* (, void* T, void* :, void* ), void* ], void* U, void* result, void* ], item ;, void* arr, void* =, void* ), void* in, void* ., void* ), void* return, void* fn) {
    __auto_type numbers = [;
    1;
    ,;
    2;
    ,;
    3;
    ];
    __auto_type result = kr_flat_map(numbers, |, |[x], *, ]);
}

void kr_partition(void* T, T :, void* ,, void* (, void* bool, void* [, void* [) {
    void* true_arr;
    T;
    ] = [;
    ];
    void* false_arr;
    T;
    ] = [;
    ];
    for (in; {; kr_predicate(item)) {
        .;
        kr_push(item);
    }
    else;
    {;
    false_arr.push(item);
}

void kr_test_partition() {
    __auto_type numbers = [;
    1;
    ,;
    2;
    ,;
    3;
    ,;
    4;
    ,;
    5;
    ,;
    6;
    ,;
    7;
    ,;
    8;
    ,;
    9;
    ,;
    10;
    ];
    int64_t (;
    evens;
    ,;
    odds;
    ) = kr_partition(numbers, |, |, _KR_EQ(%, ==), ), }, kr_test_move_closure_generic(), let, =[1], ,, ], let, =, (data), move | x | x * 2);
}

void kr_test_inference_from_return() {
    __auto_type numbers = [;
    1;
    ,;
    2;
    ,;
    3;
    ];
    void* result;
    int;
    ] = kr_map(numbers, |, |, +, ), }, kr_test_inference_from_argument(), let, :[int], [, ,, ,, ], let, =, (numbers), |, |, *, ), }, kr_test_inference_nested(), let, =[1], ,, ], let, =, (kr_map(numbers, |, |, *, ), |, |, +, ), }, kr_main(), kr_test_map_basic(), kr_test_map_transform(), kr_test_filter_basic(), kr_test_filter_strings(), kr_test_fold_sum(), kr_test_fold_product(), kr_test_fold_string_concat(), kr_test_chain_map_filter(), kr_test_chain_filter_map_fold(), kr_test_zip_basic(), kr_test_closure_capture_generic(), kr_test_closure_capture_multiple(), kr_test_make_adder(), kr_test_make_adder_with_map(), kr_test_flat_map(), kr_test_partition(), kr_test_move_closure_generic(), kr_test_inference_from_return(), kr_test_inference_from_argument(), kr_test_inference_nested(), kr_println("All generic higher-order function tests completed!"), }, )));
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
