// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
typedef struct Container Container;
int64_t kr_pair(U T, void* (, void* ,, void* ), void* ,, first return, void* second, void* fn);
T kr_identity(void* T, void* :, void* T, void* ;, void* (, x {, identity int, void* 42, void* (, void* ), void* ;, void* :, void* (, void* if, void* ), void* ;, void* ;, void* (, x {, int64_t identity, void* (, x if, void* 42, void* 1, identity y, void* bool, void* ), void* !, void* return, void* return, void* struct, value >, void* T, T make_container, void* (, Container ), void* T, T Container, void* {, void* }, T get_value, void* (, void* <);
int64_t kr_test_generic_struct();
void kr_wrap(void* T, void* :, T Container, Container {, void* T, void* :, unwrap }, void* T, void* :, void* >, c {, void* value, void* test_nested_generics, void* int, void* =, void* >);
void kr_swap(U T, void* (, U T);
int64_t kr_test_swap();
T kr_max(void* T, void* :, void* :, void* :, void* ,, void* bool, void* {, void* (, void* ), void* a, b {, void* }, void* <, T x);
int64_t kr_test_chained();
int64_t kr_main();

struct Container {
void* T;
T value;
void* ,;
T make_container;
v >;
void* :;
void* ->;
void* T;
void* return;
void* T;
v value;
};

int64_t kr_pair(U T, void* (, void* ,, void* ), void* ,, first return, void* second, void* fn) {
    __auto_type p = pair < int;
    ,;
    bool > (42);
    ,;
    true;
    );
    int64_t (;
    x;
    ,;
    y;
    ) = p;
    if (_KR_NEQ(x, 42)) {
        return 1;
    }
    if (!y) {
        return 2;
    }
    return 0;
}

T kr_identity(void* T, void* :, void* T, void* ;, void* (, x {, identity int, void* 42, void* (, void* ), void* ;, void* :, void* (, void* if, void* ), void* ;, void* ;, void* (, x {, int64_t identity, void* (, x if, void* 42, void* 1, identity y, void* bool, void* ), void* !, void* return, void* return, void* struct, value >, void* T, T make_container, void* (, Container ), void* T, T Container, void* {, void* }, T get_value, void* (, void* <) {
    return c.value;
}

int64_t kr_test_generic_struct() {
    __auto_type c = make_container < int > (42);
    if (_KR_NEQ(c.value, 42)) {
        return 1;
    }
    __auto_type v = get_value < int > (c);
    if (_KR_NEQ(v, 42)) {
        return 2;
    }
    return 0;
}

void kr_wrap(void* T, void* :, T Container, Container {, void* T, void* :, unwrap }, void* T, void* :, void* >, c {, void* value, void* test_nested_generics, void* int, void* =, void* >) {
    __auto_type unwrapped = unwrap < int > (wrapped);
    if (_KR_NEQ(unwrapped, 42)) {
        return 1;
    }
    return 0;
}

void kr_swap(U T, void* (, U T) {
    ->(U, T);
    {;
    int64_t (;
    a;
    ,;
    b;
    ) = p;
    return (b);
    ,;
    a;
    );
}

int64_t kr_test_swap() {
    __auto_type p1 = pair < int;
    ,;
    bool > (42);
    ,;
    true;
    );
    __auto_type p2 = swap < int;
    ,;
    bool > (p1);
    int64_t (;
    b;
    ,;
    i;
    ) = p2;
    if (!b) {
        return 1;
    }
    if (_KR_NEQ(i, 42)) {
        return 2;
    }
    return 0;
}

T kr_max(void* T, void* :, void* :, void* :, void* ,, void* bool, void* {, void* (, void* ), void* a, b {, void* }, void* <, T x) {
    return x;
}

int64_t kr_test_chained() {
    __auto_type result = identity < int > (identity < int > (42));
    if (_KR_NEQ(result, 42)) {
        return 1;
    }
    return 0;
}

int64_t kr_main() {
    __auto_type failures = 0;
    failures = failures + kr_test_pair();
    failures = failures + kr_test_inference_from_context();
    failures = failures + kr_test_explicit_type_args();
    failures = failures + kr_test_generic_struct();
    failures = failures + kr_test_nested_generics();
    failures = failures + kr_test_swap();
    failures = failures + kr_test_chained();
    if (_KR_EQ(failures, 0)) {
        kr_println("All advanced generics tests passed!");
    }
    return failures;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
