// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
int64_t kr_apply(U T, void* (, void* ,, void* (, void* U, transform {, void* value, void* fn);
int64_t kr_test_apply_int_to_bool();
int64_t kr_test_apply_inference();
T kr_make_multiplier(void* T, void* :, T fn);
int64_t kr_test_make_multiplier();
int64_t kr_test_closure_capture_generic();
void kr_combine(U T, void* V, void* :, void* :, void* :, void* ,, void* V, combiner {, b a);
int64_t kr_test_combine();
int64_t kr_test_combine_different_types();
int64_t kr_test_nested_closures();
int64_t kr_apply_move(U T, void* (, void* ,, void* (, void* U, transform {, void* value, void* fn);
int64_t kr_test_chained_generic();
T kr_process(void* T, void* :, void* :, T ));
int64_t kr_test_complex_closure();
int64_t kr_main();

int64_t kr_apply(U T, void* (, void* ,, void* (, void* U, transform {, void* value, void* fn) {
    __auto_type result = apply < int;
    ,;
    int > (5);
    , | x | x * 2;
    );
    if (_KR_NEQ(result, 10)) {
        return 1;
    }
    return 0;
}

int64_t kr_test_apply_int_to_bool() {
    __auto_type result = apply < int;
    ,;
    bool > (5);
    , | x | x > 3;
    );
    if (!(result){.return = ;}) {
        0;
    }
    fn;
    kr_test_apply_inference();
    ->;
    int;
    {;
    __auto_type result = kr_apply(10, |, |, +, ), _KR_NEQ(if, !=), {, 1, }, 0, }, make_multiplier < T > (factor), T);
    ->;
    fn(T);
    ->;
    (T){.return = x | x * factor};
    fn;
    kr_test_make_multiplier();
    ->;
    int;
    {;
    __auto_type times_three = make_multiplier < int > (3);
    __auto_type result = kr_times_three(7);
    if (_KR_NEQ(result, 21)) {
        return 1;
    }
    return 0;
}

int64_t kr_test_closure_capture_generic() {
    int64_t multiplier = 4;
    __auto_type result = apply < int;
    ,;
    int > (5);
    , | x | x * multiplier;
    );
    if (_KR_NEQ(result, 20)) {
        return 1;
    }
    return 0;
}

void kr_combine(U T, void* V, void* :, void* :, void* :, void* ,, void* V, combiner {, b a) {
}

int64_t kr_test_combine() {
    __auto_type result = combine < int;
    ,;
    int;
    ,;
    int > (3);
    ,;
    4;
    , | x;
    ,;
    y | x + y;
    );
    if (_KR_NEQ(result, 7)) {
        return 1;
    }
    return 0;
}

int64_t kr_test_combine_different_types() {
    __auto_type result = combine < int;
    ,;
    int;
    ,;
    bool > (5);
    ,;
    3;
    , | x;
    ,;
    y | x > y;
    );
    if (!(result){.return = ;}) {
        0;
    }
    fn;
    kr_test_nested_closures();
    ->;
    int;
    {;
    __auto_type outer = apply < int;
    ,;
    fn(int);
    ->;
    int > (2);
    , | x | {;
    return |;
    y | x + y;
}

int64_t kr_apply_move(U T, void* (, void* ,, void* (, void* U, transform {, void* value, void* fn) {
    int64_t data = 10;
    __auto_type result = apply_move < int;
    ,;
    int > (5);
    ,;
    move | x | x + data;
    );
    if (_KR_NEQ(result, 15)) {
        return 1;
    }
    return 0;
}

int64_t kr_test_chained_generic() {
    __auto_type result = apply < int;
    ,;
    int > (apply < int);
    ,;
    int > (2);
    , | x | x * 3;
    );
    , | y | y + 1;
    );
    if (_KR_NEQ(result, 7)) {
        return 1;
    }
    return 0;
}

T kr_process(void* T, void* :, void* :, T )) {
    return kr_processor(value);
}

int64_t kr_test_complex_closure() {
    __auto_type result = process < int > (10);
    , | x | {;
    __auto_type temp = x * 2;
    __auto_type temp2 = temp + 5;
    return temp2;
}

int64_t kr_main() {
    int64_t failures = 0;
    failures = failures + kr_test_apply_int_to_int();
    failures = failures + kr_test_apply_int_to_bool();
    failures = failures + kr_test_apply_inference();
    failures = failures + kr_test_make_multiplier();
    failures = failures + kr_test_closure_capture_generic();
    failures = failures + kr_test_combine();
    failures = failures + kr_test_combine_different_types();
    failures = failures + kr_test_nested_closures();
    failures = failures + kr_test_move_closure();
    failures = failures + kr_test_chained_generic();
    failures = failures + kr_test_complex_closure();
    return failures;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
