// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
typedef struct Point Point;
typedef struct Counter Counter;
typedef struct Rectangle Rectangle;
typedef int64_t Option;
typedef struct Calculator Calculator;
typedef struct Pair Pair;
typedef struct Math Math;
typedef struct Validator Validator;
typedef struct ArrayHelper ArrayHelper;
Point kr_Point_new(int64_t x, int64_t y);
Point kr_Point_origin();
void kr_test_associated_functions();
Counter kr_Counter_new();
Counter kr_Counter_with_value(int64_t v);
void kr_test_multiple_impl_blocks();
Rectangle kr_Rectangle_new(int64_t w, int64_t h);
int64_t kr_Rectangle_area(int64_t w, int64_t h);
void kr_test_visibility();
Option kr_Option_some(int64_t value);
Option kr_Option_none();
void kr_test_enum_impl();
Calculator kr_Calculator_new();
int64_t kr_Calculator_add(int64_t a, int64_t b);
int64_t kr_Calculator_multiply(int64_t a, int64_t b, int64_t c);
void kr_test_multiple_params();
Pair kr_Pair_create(int64_t a, int64_t b);
Pair kr_Pair_swap(Pair p);
void kr_test_complex_returns();
int64_t kr_Math_double(int64_t x);
int64_t kr_Math_quadruple(int64_t x);
void kr_test_nested_calls();
bool kr_Validator_is_positive(int64_t x);
int64_t kr_Validator_max(int64_t a, int64_t b);
void kr_test_conditional_methods();
int64_t kr_ArrayHelper_sum_range(int64_t start, int64_t end);
void kr_test_loop_methods();
void kr_main();

struct Point {
int64_t x;
int64_t y;
};

struct Counter {
int64_t value;
};

struct Rectangle {
int64_t width;
int64_t height;
};

typedef int64_t Option;
#define Option_Some 0
#define Option_None 1

struct Calculator {
int64_t result;
};

struct Pair {
int64_t first;
int64_t second;
};

struct Math {
int64_t dummy;
};

struct Validator {
int64_t dummy;
};

struct ArrayHelper {
int64_t dummy;
};

Point kr_Point_new(int64_t x, int64_t y) {
    return (Point){.x = x, .y = y};
}

Point kr_Point_origin() {
    return (Point){.x = 0, .y = 0};
}

void kr_test_associated_functions() {
    __auto_type p1 = Point_new;
    __auto_type p2 = Point_origin;
}

Counter kr_Counter_new() {
    return (Counter){.value = 0};
}

Counter kr_Counter_with_value(int64_t v) {
    return (Counter){.value = v};
}

void kr_test_multiple_impl_blocks() {
    __auto_type c1 = Counter_new;
    __auto_type c2 = Counter_with_value;
}

Rectangle kr_Rectangle_new(int64_t w, int64_t h) {
    return (Rectangle){.width = w, .height = h};
}

int64_t kr_Rectangle_area(int64_t w, int64_t h) {
    return w * h;
}

void kr_test_visibility() {
    __auto_type r = Rectangle_new;
}

Option kr_Option_some(int64_t value) {
    return Option_Some;
}

Option kr_Option_none() {
    return Option_None;
}

void kr_test_enum_impl() {
    __auto_type opt1 = Option_some;
    __auto_type opt2 = Option_none;
}

Calculator kr_Calculator_new() {
    return (Calculator){.result = 0};
}

int64_t kr_Calculator_add(int64_t a, int64_t b) {
    return a + b;
}

int64_t kr_Calculator_multiply(int64_t a, int64_t b, int64_t c) {
    return a * b * c;
}

void kr_test_multiple_params() {
    __auto_type calc = Calculator_new;
    __auto_type sum = Calculator_add;
    __auto_type product = Calculator_multiply;
}

Pair kr_Pair_create(int64_t a, int64_t b) {
    return (Pair){.first = a, .second = b};
}

Pair kr_Pair_swap(Pair p) {
    return (Pair){.first = p.second, .second = p.first};
}

void kr_test_complex_returns() {
    __auto_type p1 = Pair_create;
    __auto_type p2 = Pair_swap;
}

int64_t kr_Math_double(int64_t x) {
    return x * 2;
}

int64_t kr_Math_quadruple(int64_t x) {
    return Math_double;
    );
}

void kr_test_nested_calls() {
    __auto_type result = Math_quadruple;
}

bool kr_Validator_is_positive(int64_t x) {
    if (x > 0) {
        return true;
    }
    else {
        return false;
    }
}

int64_t kr_Validator_max(int64_t a, int64_t b) {
    if (a > b) {
        return a;
    }
    else {
        return b;
    }
}

void kr_test_conditional_methods() {
    __auto_type is_pos = Validator_is_positive;
    __auto_type maximum = Validator_max;
}

int64_t kr_ArrayHelper_sum_range(int64_t start, int64_t end) {
    __auto_type total = 0;
    __auto_type i = start;
    while (i < end) {
        total = total + i;
        i = i + 1;
    }
    return total;
}

void kr_test_loop_methods() {
    __auto_type sum = ArrayHelper_sum_range;
}

void kr_main() {
    kr_test_associated_functions();
    kr_test_multiple_impl_blocks();
    kr_test_visibility();
    kr_test_enum_impl();
    kr_test_multiple_params();
    kr_test_complex_returns();
    kr_test_nested_calls();
    kr_test_conditional_methods();
    kr_test_loop_methods();
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
