// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
int64_t kr_test_basic_for_in();
int64_t kr_test_for_in_with_operations();
int64_t kr_test_range_patterns();
int64_t kr_test_edge_cases();
int64_t kr_main();

int64_t kr_test_basic_for_in() {
    kr_test_section("Basic For-In Loops");
    int64_t sum = 0;
    for (i; 0; 5) {
        sum = sum + i;
    }
    kr_assert_eq(sum, 10);
    kr_test_pass("Exclusive range 0..5");
    int64_t sum2 = 0;
    for (i; 0; =) {
        {;
        sum2 = sum2 + i;
    }
    kr_assert_eq(sum2, 15);
    kr_test_pass("Inclusive range 0..=5");
    int64_t sum3 = 0;
    for (i; 5; 10) {
        sum3 = sum3 + i;
    }
    kr_assert_eq(sum3, 35);
    kr_test_pass("Range 5..10");
    int64_t count = 0;
    for (i; 10; 11) {
        count = count + 1;
        kr_assert_eq(i, 10);
    }
    kr_assert_eq(count, 1);
    kr_test_pass("Single iteration range");
    int64_t count2 = 0;
    for (i; 5; 5) {
        count2 = count2 + 1;
    }
    kr_assert_eq(count2, 0);
    kr_test_pass("Empty range (exclusive)");
    0;
}

int64_t kr_test_for_in_with_operations() {
    kr_test_section("For-In with Operations");
    int64_t product = 1;
    for (i; 1; =) {
        {;
        product = product * i;
    }
    kr_assert_eq(product, 120);
    kr_test_pass("Factorial using for-in");
    int64_t even_count = 0;
    for (i; 0; 10) {
        if (_KR_EQ(i % 2, 0)) {
            even_count = even_count + 1;
        }
    }
    kr_assert_eq(even_count, 5);
    kr_test_pass("Count even numbers");
    int64_t total = 0;
    for (i; 0; 3) {
        for (j; 0; 3) {
            total = total + i + j;
        }
    }
    kr_assert_eq(total, 18);
    kr_test_pass("Nested for-in loops");
    0;
}

int64_t kr_test_range_patterns() {
    kr_test_section("Range Patterns in Match");
    int64_t x = 5;
    if (x == 0) {
        ..;
        10;
        ->;
        {;
        kr_test_pass("Range pattern 0..10 matches 5");
    }
    else {
        kr_test_fail("Should match range");
    }
    int64_t y = 10;
    if (y == 0) {
        .. = 10;
        ->;
        {;
        kr_test_pass("Inclusive range 0..=10 matches 10");
    }
    else {
        kr_test_fail("Should match inclusive range");
    }
    int64_t z = 15;
    if (z == 0) {
        ..;
        10;
        ->;
        {;
        kr_test_fail("Should not match range");
    }
    else {
        kr_test_pass("Wildcard matches 15");
    }
    int64_t val = 25;
    if (val == 0) {
        ..;
        10;
        ->;
        {;
        kr_test_fail("Should not match 0..10");
    }
    else if (val == 10) {
        ..;
        20;
        ->;
        {;
        kr_test_fail("Should not match 10..20");
    }
    else if (val == 20) {
        ..;
        30;
        ->;
        {;
        kr_test_pass("Matches 20..30");
    }
    else {
        kr_test_fail("Should match range");
    }
    0;
}

int64_t kr_test_edge_cases() {
    kr_test_section("Edge Cases");
    int64_t count = 0;
    for (i; 0; 100) {
        count = count + 1;
    }
    kr_assert_eq(count, 100);
    kr_test_pass("Large range 0..100");
    int64_t sum3 = 0;
    for (i; 0; 100) {
        if (_KR_EQ(i, 5)) {
            break;
        }
        sum3 = sum3 + i;
    }
    kr_assert_eq(sum3, 10);
    kr_test_pass("Break in for-in loop");
    int64_t sum4 = 0;
    for (i; 0; 10) {
        if (_KR_EQ(i % 2, 1)) {
            continue;
        }
        sum4 = sum4 + i;
    }
    kr_assert_eq(sum4, 20);
    kr_test_pass("Continue in for-in loop");
    0;
}

int64_t kr_main() {
    kr_puts("=== RANGE AND FOR-IN LOOP TESTS ===");
    kr_puts("");
    kr_test_basic_for_in();
    kr_test_for_in_with_operations();
    kr_test_range_patterns();
    kr_test_edge_cases();
    kr_puts("");
    kr_puts("=== ALL TESTS PASSED ===");
    0;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
