// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
typedef struct Point Point;
typedef struct Point3D Point3D;
typedef struct Person Person;
int64_t kr_test_basic_struct_pattern();
int64_t kr_test_partial_struct_pattern();
int64_t kr_test_struct_pattern_with_wildcard();
int64_t kr_test_multiple_struct_patterns();
int64_t kr_test_nested_field_access();
int64_t kr_test_struct_pattern_exhaustiveness();
int64_t kr_test_struct_shorthand();
int64_t kr_test_edge_cases();
int64_t kr_main();

struct Point {
int64_t x;
void* ,;
void* int;
void* struct;
int64_t x;
void* ,;
z int;
void* :;
};

struct Person {
kr_str name;
void* ,;
void* int;
void* fn;
int64_t );
void* {;
void* Basic Struct Patterns;
void* let;
Point Point;
void* {;
y 10;
void* :;
p match;
Point );
void* {;
void* y;
void* {;
void* x;
void* &&;
void* 20;
void* test_pass;
void* );
test_fail else;
void* (;
};

int64_t kr_test_basic_struct_pattern() {
    kr_test_section("Basic Struct Patterns");
    Point p = (Point){.x = 10, .y = 20};
    if (p == Point) {
        x;
        ,;
        y;
    }
    else if (p == ->) {
        if (_KR_EQ(x, 10) && _KR_EQ(y, 20)) {
            kr_test_pass("Basic struct pattern matches and binds fields");
        }
        else {
            kr_test_fail("Field values incorrect");
        }
    }
    0;
}

int64_t kr_test_partial_struct_pattern() {
    kr_test_section("Partial Struct Patterns");
    Point3D p = (Point3D){.x = 1, .y = 2, .z = 3};
    if (p == Point3D) {
        x;
        ,;
        ..;
    }
    else if (p == ->) {
        if (_KR_EQ(x, 1)) {
            kr_test_pass("Partial struct pattern with .. works");
        }
        else {
            kr_test_fail("Field x value incorrect");
        }
    }
    0;
}

int64_t kr_test_struct_pattern_with_wildcard() {
    kr_test_section("Struct Pattern with Wildcard");
    Point p = (Point){.x = 5, .y = 10};
    if (p == Point) {
        x;
        :;
        _;
        ,;
        y;
    }
    else if (p == ->) {
        if (_KR_EQ(y, 10)) {
            kr_test_pass("Struct pattern with wildcard field works");
        }
        else {
            kr_test_fail("Field y value incorrect");
        }
    }
    0;
}

int64_t kr_test_multiple_struct_patterns() {
    kr_test_section("Multiple Struct Patterns");
    Point p1 = (Point){.x = 0, .y = 0};
    Point p2 = (Point){.x = 1, .y = 1};
    Point p3 = (Point){.x = 5, .y = 10};
    if (p1 == Point) {
        x;
        :;
        0;
        ,;
        y;
        :;
        0;
    }
    else if (p1 == ->) {
        kr_test_pass("Origin point matched");
    }
    else {
        kr_test_fail("Should match origin");
    }
    if (p2 == Point) {
        x;
        :;
        0;
        ,;
        y;
        :;
        0;
    }
    else if (p2 == ->) {
        kr_test_fail("Should not match origin");
    }
    else if (p2 == Point) {
        x;
        :;
        1;
        ,;
        y;
        :;
        1;
    }
    else if (p2 == ->) {
        kr_test_pass("Unit point matched");
    }
    else {
        kr_test_fail("Should match unit point");
    }
    if (p3 == Point) {
        x;
        :;
        0;
        ,;
        y;
        :;
        0;
    }
    else if (p3 == ->) {
        kr_test_fail("Should not match origin");
    }
    else if (p3 == Point) {
        x;
        :;
        1;
        ,;
        y;
        :;
        1;
    }
    else if (p3 == ->) {
        kr_test_fail("Should not match unit");
    }
    else {
        kr_test_pass("Wildcard matches other points");
    }
    0;
}

int64_t kr_test_nested_field_access() {
    kr_test_section("Nested Field Access in Patterns");
    Point p = (Point){.x = 100, .y = 200};
    if (p == Point) {
        x;
        ,;
        y;
    }
    else if (p == ->) {
        int64_t sum = x + y;
        if (_KR_EQ(sum, 300)) {
            kr_test_pass("Can use destructured fields in expressions");
        }
        else {
            kr_test_fail("Field arithmetic incorrect");
        }
    }
    0;
}

int64_t kr_test_struct_pattern_exhaustiveness() {
    kr_test_section("Struct Pattern Exhaustiveness");
    Point p = (Point){.x = 42, .y = 24};
    if (p == Point) {
        x;
        :;
        0;
        ,;
        y;
        :;
        0;
    }
    else if (p == ->) {
        kr_test_fail("Not origin");
    }
    else {
        kr_test_pass("Wildcard makes match exhaustive");
    }
    0;
}

int64_t kr_test_struct_shorthand() {
    kr_test_section("Struct Pattern Shorthand");
    Point p = (Point){.x = 7, .y = 14};
    if (p == Point) {
        x;
        ,;
        y;
    }
    else if (p == ->) {
        if (_KR_EQ(x, 7) && _KR_EQ(y, 14)) {
            kr_test_pass("Shorthand syntax works");
        }
        else {
            kr_test_fail("Shorthand values incorrect");
        }
    }
    0;
}

int64_t kr_test_edge_cases() {
    kr_test_section("Edge Cases");
    Point p1 = (Point){.x = 0, .y = 0};
    if (p1 == Point) {
        x;
        :;
        0;
        ,;
        y;
        :;
        0;
    }
    else if (p1 == ->) {
        kr_test_pass("Zero values match correctly");
    }
    else {
        kr_test_fail("Should match zero values");
    }
    Point p2 = (Point){.x = -5, .y = -10};
    if (p2 == Point) {
        x;
        ,;
        y;
    }
    else if (p2 == ->) {
        if (_KR_EQ(x, -5) && _KR_EQ(y, -10)) {
            kr_test_pass("Negative values work in patterns");
        }
        else {
            kr_test_fail("Negative values incorrect");
        }
    }
    Point p3 = (Point){.x = 1000000, .y = 2000000};
    if (p3 == Point) {
        x;
        ,;
        y;
    }
    else if (p3 == ->) {
        if (_KR_EQ(x, 1000000) && _KR_EQ(y, 2000000)) {
            kr_test_pass("Large values work in patterns");
        }
        else {
            kr_test_fail("Large values incorrect");
        }
    }
    0;
}

int64_t kr_main() {
    kr_puts("=== STRUCT PATTERNS TESTS ===");
    kr_puts("");
    kr_test_basic_struct_pattern();
    kr_test_partial_struct_pattern();
    kr_test_struct_pattern_with_wildcard();
    kr_test_multiple_struct_patterns();
    kr_test_nested_field_access();
    kr_test_struct_pattern_exhaustiveness();
    kr_test_struct_shorthand();
    kr_test_edge_cases();
    kr_puts("");
    kr_puts("=== ALL STRUCT PATTERN TESTS PASSED ===");
    0;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
