// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
typedef struct S1p S1p;
typedef struct S2p S2p;
typedef struct S3p S3p;
typedef struct S2pi S2pi;
S1p kr_adv1p(S1p s);
S2p kr_adv2p(S2p s);
S3p kr_adv3p(S3p s);
S2pi kr_adv2pi(S2pi s);
int64_t kr_main();

struct S1p {
void* a;
};

struct S2p {
int64_t a;
void* b;
};

struct S3p {
int64_t a;
int64_t b;
void* c;
};

struct S2pi {
void* a;
int64_t b;
};

S1p kr_adv1p(S1p s) {
    return (S1p){.a = s.a};
}

S2p kr_adv2p(S2p s) {
    return (S2p){.a = s.a + 1, .b = s.b};
}

S3p kr_adv3p(S3p s) {
    return (S3p){.a = s.a + 1, .b = s.b, .c = s.c};
}

S2pi kr_adv2pi(S2pi s) {
    return (S2pi){.a = s.a, .b = s.b + 1};
}

int64_t kr_main() {
    void* v1 = kr_vec_int_new();
    void* v2 = kr_vec_int_new();
    void* v3 = kr_vec_int_new();
    void* v4 = kr_vec_int_new();
    S1p s1 = (S1p){.a = v1};
    s1 = kr_adv1p(s1);
    kr_vec_int_push(s1.a, 11);
    kr_puts(kr_str_concat("S1p ok, val=", kr_fmt_int(kr_vec_int_get(s1.a, 0))));
    S2p s2 = (S2p){.a = 0, .b = v2};
    s2 = kr_adv2p(s2);
    kr_puts(kr_str_concat("S2p a=", kr_fmt_int(s2.a)));
    kr_vec_int_push(s2.b, 22);
    kr_puts(kr_str_concat("S2p ok, val=", kr_fmt_int(kr_vec_int_get(s2.b, 0))));
    S3p s3 = (S3p){.a = 0, .b = 10, .c = v3};
    s3 = kr_adv3p(s3);
    kr_puts(kr_str_concat("S3p a=", kr_fmt_int(s3.a)));
    kr_vec_int_push(s3.c, 33);
    kr_puts(kr_str_concat("S3p ok, val=", kr_fmt_int(kr_vec_int_get(s3.c, 0))));
    S2pi s2i = (S2pi){.a = v4, .b = 0};
    s2i = kr_adv2pi(s2i);
    kr_puts(kr_str_concat("S2pi b=", kr_fmt_int(s2i.b)));
    kr_vec_int_push(s2i.a, 44);
    kr_puts(kr_str_concat("S2pi ok, val=", kr_fmt_int(kr_vec_int_get(s2i.a, 0))));
    kr_vec_int_free(v1);
    kr_vec_int_free(v2);
    kr_vec_int_free(v3);
    kr_vec_int_free(v4);
    return 0;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
