// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
typedef struct S3 S3;
typedef struct S4 S4;
typedef struct S5 S5;
typedef struct S6 S6;
S3 kr_adv3(S3 s);
S4 kr_adv4(S4 s);
S5 kr_adv5(S5 s);
S6 kr_adv6(S6 s);
int64_t kr_main();

struct S3 {
int64_t a;
int64_t b;
int64_t c;
};

struct S4 {
int64_t a;
int64_t b;
int64_t c;
int64_t d;
};

struct S5 {
int64_t a;
int64_t b;
int64_t c;
int64_t d;
int64_t e;
};

struct S6 {
int64_t a;
int64_t b;
int64_t c;
int64_t d;
int64_t e;
int64_t f;
};

S3 kr_adv3(S3 s) {
    return (S3){.a = s.a + 1, .b = s.b, .c = s.c};
}

S4 kr_adv4(S4 s) {
    return (S4){.a = s.a + 1, .b = s.b, .c = s.c, .d = s.d};
}

S5 kr_adv5(S5 s) {
    return (S5){.a = s.a + 1, .b = s.b, .c = s.c, .d = s.d, .e = s.e};
}

S6 kr_adv6(S6 s) {
    return (S6){.a = s.a + 1, .b = s.b, .c = s.c, .d = s.d, .e = s.e, .f = s.f};
}

int64_t kr_main() {
    S3 s3 = (S3){.a = 0, .b = 10, .c = 20};
    s3 = kr_adv3(s3);
    kr_puts(kr_str_concat("S3 a=", kr_fmt_int(s3.a)));
    kr_puts(kr_str_concat("S3 c=", kr_fmt_int(s3.c)));
    S4 s4 = (S4){.a = 0, .b = 10, .c = 20, .d = 30};
    s4 = kr_adv4(s4);
    kr_puts(kr_str_concat("S4 a=", kr_fmt_int(s4.a)));
    kr_puts(kr_str_concat("S4 d=", kr_fmt_int(s4.d)));
    S5 s5 = (S5){.a = 0, .b = 10, .c = 20, .d = 30, .e = 40};
    s5 = kr_adv5(s5);
    kr_puts(kr_str_concat("S5 a=", kr_fmt_int(s5.a)));
    kr_puts(kr_str_concat("S5 e=", kr_fmt_int(s5.e)));
    S6 s6 = (S6){.a = 0, .b = 10, .c = 20, .d = 30, .e = 40, .f = 50};
    s6 = kr_adv6(s6);
    kr_puts(kr_str_concat("S6 a=", kr_fmt_int(s6.a)));
    kr_puts(kr_str_concat("S6 f=", kr_fmt_int(s6.f)));
    return 0;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
