// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
double kr_kraken_sin(double x);
double kr_kraken_cos(double x);
double kr_kraken_tan(double x);
double kr_kraken_asin(double x);
double kr_kraken_acos(double x);
double kr_kraken_atan(double x);
double kr_kraken_atan2(double y, double x);
double kr_kraken_sinh(double x);
double kr_kraken_cosh(double x);
double kr_kraken_tanh(double x);
double kr_kraken_exp(double x);
double kr_kraken_log(double x);
double kr_kraken_log10(double x);
double kr_kraken_log2(double x);
double kr_kraken_pow(double base, double exp);
double kr_kraken_sqrt(double x);
double kr_kraken_cbrt(double x);
double kr_kraken_ceil(double x);
double kr_kraken_floor(double x);
double kr_kraken_round(double x);
double kr_kraken_trunc(double x);
double kr_kraken_fmod(double x, double y);
double kr_kraken_remainder(double x, double y);
double kr_kraken_fabs(double x);
double kr_kraken_hypot(double x, double y);
int64_t kr_kraken_time();
int64_t kr_kraken_clock();
int64_t kr_kraken_clocks_per_sec();
double kr_kraken_difftime(int64_t time1, int64_t time0);
kr_str kr_kraken_strftime(kr_str format, int64_t timestamp);
int64_t kr_kraken_calloc(int64_t count, int64_t size);
int64_t kr_kraken_aligned_alloc(int64_t alignment, int64_t size);
int64_t kr_kraken_realloc(int64_t ptr, int64_t new_size);
void kr_kraken_free(int64_t ptr);
int64_t kr_kraken_memcpy(int64_t dest, int64_t src, int64_t n);
int64_t kr_kraken_memset(int64_t s, int64_t c, int64_t n);
int64_t kr_kraken_memcmp(int64_t s1, int64_t s2, int64_t n);
int64_t kr_test_trig_functions();
int64_t kr_test_inverse_trig();
int64_t kr_test_hyperbolic();
int64_t kr_test_exponential_log();
int64_t kr_test_power_root();
int64_t kr_test_rounding();
int64_t kr_test_remainder();
int64_t kr_test_other_math();
int64_t kr_test_time_functions();
int64_t kr_test_difftime();
int64_t kr_test_strftime();
int64_t kr_test_calloc();
int64_t kr_test_aligned_alloc();
int64_t kr_main();

double kr_kraken_sin(double x) {
    extern;
    fn;
    kr_kraken_cos(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_tan(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_asin(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_acos(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_atan(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_atan2(y, float, x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_sinh(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_cosh(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_tanh(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_exp(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_log(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_log10(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_log2(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_pow(base, float, exp, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_sqrt(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_cbrt(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_ceil(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_floor(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_round(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_trunc(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_fmod(x, float, y, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_remainder(x, float, y, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_fabs(x, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_hypot(x, float, y, float);
    ->;
    float;
    extern;
    fn;
    kr_kraken_time();
    ->;
    int;
    extern;
    fn;
    kr_kraken_clock();
    ->;
    int;
    extern;
    fn;
    kr_kraken_clocks_per_sec();
    ->;
    int;
    extern;
    fn;
    kr_kraken_difftime(time1, int, time0, int);
    ->;
    float;
    extern;
    fn;
    kr_kraken_strftime(format, str, timestamp, int);
    ->;
    str;
    extern;
    fn;
    kr_kraken_calloc(count, int, size, int);
    ->;
    int;
    extern;
    fn;
    kr_kraken_aligned_alloc(alignment, int, size, int);
    ->;
    int;
    extern;
    fn;
    kr_kraken_realloc(ptr, int, new_size, int);
    ->;
    int;
    extern;
    fn;
    kr_kraken_free(ptr, int);
    ->;
    void;
    extern;
    fn;
    kr_kraken_memcpy(dest, int, src, int, n, int);
    ->;
    int;
    extern;
    fn;
    kr_kraken_memset(s, int, c, int, n, int);
    ->;
    int;
    extern;
    fn;
    kr_kraken_memcmp(s1, int, s2, int, n, int);
    ->;
    int;
    fn;
    kr_test_trig_functions();
    ->;
    int;
    {;
    __auto_type pi = 3.14159265359;
    __auto_type sin_val = kr_kraken_sin(pi / 2.0);
    __auto_type cos_val = kr_kraken_cos(0.0);
    __auto_type tan_val = kr_kraken_tan(0.0);
    kr_puts("Trig functions tested");
    return 0;
}

int64_t kr_test_inverse_trig() {
    __auto_type asin_val = kr_kraken_asin(0.5);
    __auto_type acos_val = kr_kraken_acos(0.5);
    __auto_type atan_val = kr_kraken_atan(1.0);
    __auto_type atan2_val = kr_kraken_atan2(1.0, 1.0);
    kr_puts("Inverse trig functions tested");
    return 0;
}

int64_t kr_test_hyperbolic() {
    __auto_type sinh_val = kr_kraken_sinh(1.0);
    __auto_type cosh_val = kr_kraken_cosh(1.0);
    __auto_type tanh_val = kr_kraken_tanh(1.0);
    kr_puts("Hyperbolic functions tested");
    return 0;
}

int64_t kr_test_exponential_log() {
    __auto_type exp_val = kr_kraken_exp(1.0);
    __auto_type log_val = kr_kraken_log(2.71828);
    __auto_type log10_val = kr_kraken_log10(100.0);
    __auto_type log2_val = kr_kraken_log2(8.0);
    kr_puts("Exponential and log functions tested");
    return 0;
}

int64_t kr_test_power_root() {
    __auto_type pow_val = kr_kraken_pow(2.0, 3.0);
    __auto_type sqrt_val = kr_kraken_sqrt(16.0);
    __auto_type cbrt_val = kr_kraken_cbrt(27.0);
    kr_puts("Power and root functions tested");
    return 0;
}

int64_t kr_test_rounding() {
    __auto_type ceil_val = kr_kraken_ceil(3.14);
    __auto_type floor_val = kr_kraken_floor(3.14);
    __auto_type round_val = kr_kraken_round(3.14);
    __auto_type trunc_val = kr_kraken_trunc(3.14);
    kr_puts("Rounding functions tested");
    return 0;
}

int64_t kr_test_remainder() {
    __auto_type fmod_val = kr_kraken_fmod(7.0, 3.0);
    __auto_type rem_val = kr_kraken_remainder(7.0, 3.0);
    kr_puts("Remainder functions tested");
    return 0;
}

int64_t kr_test_other_math() {
    __auto_type abs_val = kr_kraken_fabs(-5.5);
    __auto_type hypot_val = kr_kraken_hypot(3.0, 4.0);
    kr_puts("Other math functions tested");
    return 0;
}

int64_t kr_test_time_functions() {
    __auto_type current_time = kr_kraken_time();
    __auto_type clock_ticks = kr_kraken_clock();
    __auto_type clocks_per_sec = kr_kraken_clocks_per_sec();
    if (current_time > 0) {
        kr_puts("Time functions working");
    }
    return 0;
}

int64_t kr_test_difftime() {
    __auto_type time1 = kr_kraken_time();
    __auto_type time0 = time1 - 3600;
    __auto_type diff = kr_kraken_difftime(time1, time0);
    kr_puts("Difftime tested");
    return 0;
}

int64_t kr_test_strftime() {
    __auto_type current_time = kr_kraken_time();
    __auto_type formatted = kr_kraken_strftime("%Y-%m-%d %H:%M:%S", current_time);
    if (_KR_NEQ(formatted, 0)) {
        kr_puts(formatted);
    }
    return 0;
}

int64_t kr_test_calloc() {
    __auto_type ptr = kr_kraken_calloc(10, 4);
    if (_KR_NEQ(ptr, 0)) {
        kr_kraken_free(ptr);
        kr_puts("Calloc tested");
    }
    return 0;
}

int64_t kr_test_aligned_alloc() {
    __auto_type ptr = kr_kraken_aligned_alloc(16, 64);
    if (_KR_NEQ(ptr, 0)) {
        kr_kraken_free(ptr);
        kr_puts("Aligned alloc tested");
    }
    return 0;
}

int64_t kr_main() {
    __auto_type failures = 0;
    kr_puts("Testing standard library expansion...");
    kr_puts("");
    kr_puts("=== Math Functions ===");
    failures = failures + kr_test_trig_functions();
    failures = failures + kr_test_inverse_trig();
    failures = failures + kr_test_hyperbolic();
    failures = failures + kr_test_exponential_log();
    failures = failures + kr_test_power_root();
    failures = failures + kr_test_rounding();
    failures = failures + kr_test_remainder();
    failures = failures + kr_test_other_math();
    kr_puts("");
    kr_puts("=== Time Functions ===");
    failures = failures + kr_test_time_functions();
    failures = failures + kr_test_difftime();
    failures = failures + kr_test_strftime();
    kr_puts("");
    kr_puts("=== Memory Functions ===");
    failures = failures + kr_test_calloc();
    failures = failures + kr_test_aligned_alloc();
    kr_puts("");
    if (_KR_EQ(failures, 0)) {
        kr_puts("All standard library expansion tests passed!");
    }
    return failures;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
