// Generated by krakenc — Kraken Self-Hosted Compiler
// Target: x86_64-apple-darwin

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <unistd.h>

typedef int64_t kr_int;
typedef double kr_float;
typedef bool kr_bool;
typedef char* kr_str;
typedef ssize_t kr_size;

void kr_puts(kr_str s) { puts(s); }
int64_t kr_strlen(kr_str s) { return (int64_t)strlen(s); }
int64_t kr_abs(int64_t x) { return x < 0 ? -x : x; }
int kr_strcmp(kr_str a, kr_str b) { return strcmp(a, b); }
static inline bool _kr_str_eq(kr_str a, kr_str b) { return strcmp(a,b)==0; }
static inline bool _kr_str_neq(kr_str a, kr_str b) { return strcmp(a,b)!=0; }
static inline int _kr_cmp_eq(void* a, void* b) { return strcmp((char*)a,(char*)b)==0; }
static inline int _kr_cmp_neq(void* a, void* b) { return strcmp((char*)a,(char*)b)!=0; }
static inline int _kr_int_eq(int64_t a, int64_t b) { return a==b; }
static inline int _kr_int_neq(int64_t a, int64_t b) { return a!=b; }
#define _KR_EQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_eq((void*)(a),(void*)(b)), _kr_int_eq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#define _KR_NEQ(a, b) __builtin_choose_expr(__builtin_types_compatible_p(__typeof__(a), char*), _kr_cmp_neq((void*)(a),(void*)(b)), _kr_int_neq((int64_t)(intptr_t)(a),(int64_t)(intptr_t)(b)))
#pragma clang diagnostic ignored "-Wint-to-void-pointer-cast"
kr_str kr_str_concat(kr_str a, kr_str b) {
  size_t la = strlen(a), lb = strlen(b);
  char* r = (char*)malloc(la + lb + 1);
  memcpy(r, a, la); memcpy(r + la, b, lb); r[la+lb] = 0; return r;
}
int64_t kr_str_char_at(kr_str s, int64_t i) { return (int64_t)(unsigned char)s[i]; }
kr_str kr_str_slice(kr_str s, int64_t start, int64_t end) {
  int64_t len = end - start; char* r = (char*)malloc(len + 1);
  memcpy(r, s + start, len); r[len] = 0; return r;
}
bool kr_str_ends_with(kr_str s, kr_str suffix) {
  size_t ls = strlen(s), lx = strlen(suffix);
  return lx <= ls && strcmp(s + ls - lx, suffix) == 0;
}
kr_str kr_fmt_int(int64_t v) {
  char* r = (char*)malloc(32); snprintf(r, 32, "%lld", (long long)v); return r;
}
kr_str kr_getenv(kr_str name) {
  char* v = (char*)getenv(name); return v ? v : (char*)"";
}
int64_t kr_system(kr_str cmd) { return (int64_t)system(cmd); }
void kr_exit(int64_t code) { exit((int)code); }
void* kr_fopen(kr_str path, kr_str mode) { return (void*)fopen(path, mode); }
void kr_fclose(void* f) { fclose((FILE*)f); }
void kr_fputs(kr_str s, void* f) { fputs(s, (FILE*)f); }
kr_str kr_file_read_string(kr_str path) {
  FILE* f = fopen(path, "rb"); if(!f) return "";
  fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
  char* buf = (char*)malloc(sz + 1); fread(buf, 1, sz, f); buf[sz] = 0;
  fclose(f); return buf;
}
typedef struct { int64_t* data; int64_t len; int64_t cap; } KrVecInt;
void* kr_vec_int_new() {
  KrVecInt* v = (KrVecInt*)malloc(sizeof(KrVecInt));
  v->data = (int64_t*)malloc(16 * sizeof(int64_t)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_int_push(void* vp, int64_t val) {
  KrVecInt* v = (KrVecInt*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (int64_t*)realloc(v->data, v->cap * sizeof(int64_t)); }
  v->data[v->len++] = val;
}
int64_t kr_vec_int_get(void* vp, int64_t i) { return ((KrVecInt*)vp)->data[i]; }
void kr_vec_int_set(void* vp, int64_t i, int64_t val) { ((KrVecInt*)vp)->data[i] = val; }
int64_t kr_vec_int_len(void* vp) { return ((KrVecInt*)vp)->len; }
void kr_vec_int_free(void* vp) { KrVecInt* v = (KrVecInt*)vp; free(v->data); free(v); }
typedef struct { char** data; int64_t len; int64_t cap; } KrVecString;
void* kr_vec_string_new() {
  KrVecString* v = (KrVecString*)malloc(sizeof(KrVecString));
  v->data = (char**)malloc(16 * sizeof(char*)); v->len = 0; v->cap = 16; return v;
}
void kr_vec_string_push(void* vp, kr_str val) {
  KrVecString* v = (KrVecString*)vp;
  if(v->len >= v->cap) { v->cap *= 2; v->data = (char**)realloc(v->data, v->cap * sizeof(char*)); }
  v->data[v->len++] = val;
}
kr_str kr_vec_string_get(void* vp, int64_t i) { return ((KrVecString*)vp)->data[i]; }
void kr_vec_string_set(void* vp, int64_t i, kr_str val) { ((KrVecString*)vp)->data[i] = val; }
int64_t kr_vec_string_len(void* vp) { return ((KrVecString*)vp)->len; }
void kr_vec_string_free(void* vp) { KrVecString* v = (KrVecString*)vp; free(v->data); free(v); }

/* Forward declarations */
int64_t kr_kraken_malloc_tracked(int64_t size, kr_str file, int64_t line);
int64_t kr_kraken_calloc_tracked(int64_t count, int64_t size, kr_str file, int64_t line);
int64_t kr_kraken_realloc_tracked(int64_t ptr, int64_t new_size, kr_str file, int64_t line);
void kr_kraken_free_tracked(int64_t ptr);
int64_t kr_kraken_get_allocation_count();
int64_t kr_kraken_get_allocated_bytes();
void kr_kraken_print_allocation_stats();
int64_t kr_test_malloc_free_tracking();
int64_t kr_test_calloc_tracking();
int64_t kr_test_realloc_tracking();
int64_t kr_test_allocation_stats();
int64_t kr_test_intentional_leak();
int64_t kr_main();

int64_t kr_kraken_malloc_tracked(int64_t size, kr_str file, int64_t line) {
    extern;
    fn;
    kr_kraken_calloc_tracked(count, int, size, int, file, str, line, int);
    ->;
    int;
    extern;
    fn;
    kr_kraken_realloc_tracked(ptr, int, new_size, int, file, str, line, int);
    ->;
    int;
    extern;
    fn;
    kr_kraken_free_tracked(ptr, int);
    ->;
    void;
    extern;
    fn;
    kr_kraken_get_allocation_count();
    ->;
    int;
    extern;
    fn;
    kr_kraken_get_allocated_bytes();
    ->;
    int;
    extern;
    fn;
    kr_kraken_print_allocation_stats();
    ->;
    void;
    fn;
    kr_test_malloc_free_tracking();
    ->;
    int;
    {;
    kr_puts("Testing malloc/free tracking...");
    __auto_type initial_count = kr_kraken_get_allocation_count();
    __auto_type ptr1 = kr_kraken_malloc_tracked(100, "test_leak_detection.kr", 19);
    __auto_type ptr2 = kr_kraken_malloc_tracked(200, "test_leak_detection.kr", 20);
    __auto_type after_alloc = kr_kraken_get_allocation_count();
    kr_kraken_free_tracked(ptr1);
    kr_kraken_free_tracked(ptr2);
    __auto_type after_free = kr_kraken_get_allocation_count();
    if (initial_count >= 0) {
        kr_puts("Malloc/free tracking test passed");
    }
    return 0;
}

int64_t kr_test_calloc_tracking() {
    kr_puts("Testing calloc tracking...");
    __auto_type ptr = kr_kraken_calloc_tracked(10, 4, "test_leak_detection.kr", 42);
    if (_KR_NEQ(ptr, 0)) {
        kr_kraken_free_tracked(ptr);
        kr_puts("Calloc tracking test passed");
    }
    return 0;
}

int64_t kr_test_realloc_tracking() {
    kr_puts("Testing realloc tracking...");
    __auto_type ptr = kr_kraken_malloc_tracked(100, "test_leak_detection.kr", 56);
    if (_KR_NEQ(ptr, 0)) {
        __auto_type new_ptr = kr_kraken_realloc_tracked(ptr, 200, "test_leak_detection.kr", 59);
        if (_KR_NEQ(new_ptr, 0)) {
            kr_kraken_free_tracked(new_ptr);
            kr_puts("Realloc tracking test passed");
        }
    }
    return 0;
}

int64_t kr_test_allocation_stats() {
    kr_puts("Testing allocation statistics...");
    __auto_type count = kr_kraken_get_allocation_count();
    __auto_type bytes = kr_kraken_get_allocated_bytes();
    if (count >= 0) {
        kr_puts("Allocation statistics test passed");
    }
    return 0;
}

int64_t kr_test_intentional_leak() {
    kr_puts("Testing intentional leak detection...");
    kr_puts("(This will show a leak if KRAKEN_LEAK_CHECK=1)");
    __auto_type leaked_ptr = kr_kraken_malloc_tracked(42, "test_leak_detection.kr", 90);
    if (_KR_NEQ(leaked_ptr, 0)) {
        kr_puts("Intentional leak created for testing");
    }
    return 0;
}

int64_t kr_main() {
    __auto_type failures = 0;
    kr_puts("Testing memory leak detection infrastructure...");
    kr_puts("Note: Set KRAKEN_LEAK_CHECK=1 to enable leak tracking");
    kr_puts("");
    failures = failures + kr_test_malloc_free_tracking();
    failures = failures + kr_test_calloc_tracking();
    failures = failures + kr_test_realloc_tracking();
    failures = failures + kr_test_allocation_stats();
    kr_puts("");
    kr_puts("Allocation statistics:");
    kr_kraken_print_allocation_stats();
    kr_puts("");
    failures = failures + kr_test_intentional_leak();
    kr_puts("");
    if (_KR_EQ(failures, 0)) {
        kr_puts("All leak detection tests passed!");
        kr_puts("Check for leak report at program exit if KRAKEN_LEAK_CHECK=1");
    }
    return failures;
}


int main(int argc, char* argv[]) {
    return (int)kr_main();
}
