#####################################################
#  ▗▖ ▄▖          ▗▖             
#  ▐▌▐▛           ▐▌             
#  ▐▙█   █▟█▌ ▟██▖▐▌▟▛  ▟█▙ ▐▙██▖
#  ▐██   █▘   ▘▄▟▌▐▙█  ▐▙▄▟▌▐▛ ▐▌
#  ▐▌▐▙  █   ▗█▀▜▌▐▛█▖ ▐▛▀▀▘▐▌ ▐▌
#  ▐▌ █▖ █   ▐▙▄█▌▐▌▝▙ ▝█▄▄▌▐▌ ▐▌
#  ▝▘ ▝▘ ▀    ▀▀▝▘▝▘ ▀▘ ▝▀▀ ▝▘ ▝▘
#
#####################################################
[package]
#####################################################
name = "kraken"
# ========================
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
# ========================
documentation.workspace = true
repository.workspace    = true
homepage.workspace      = true
# ========================
publish = false


# Binaries
#####################################################
[[bin]]
name = "kraken"
path = "src/main.rs"

[[bench]]
name = "stdlib_sig"
harness = false


# Dependencies
[dependencies]
#####################################################

# Local Dependencies
kraken-runtime = { path = "../runtime" }

# External Dependencies
serde = { workspace = true }
serde_json = { workspace = true }
toml = "0.8"
anyhow = { workspace = true }
thiserror = { workspace = true }
llvm-sys = { workspace = true }
clap = { workspace = true }
num_cpus = "1.16"
rustc_version = "0.4"

# CLI Output Enhancement
colored = "2.1"
figlet-rs = "0.1"
indicatif = "0.17"
comfy-table = "7.1"

# Async Runtime
tokio = { workspace = true }

# File Discovery
glob = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }